/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 01:54:25 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import java.net.Authenticator;
import java.net.InetAddress;
import java.net.PasswordAuthentication;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockInetAddress;
import org.jsoup.helper.AuthenticationHandler;
import org.jsoup.helper.RequestAuthenticator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class AuthenticationHandler_ESTest extends AuthenticationHandler_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      AuthenticationHandler.GlobalHandler authenticationHandler_GlobalHandler0 = new AuthenticationHandler.GlobalHandler();
      AuthenticationHandler authenticationHandler0 = new AuthenticationHandler((RequestAuthenticator) null);
      authenticationHandler_GlobalHandler0.enable((RequestAuthenticator) null, authenticationHandler0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      InetAddress inetAddress0 = MockInetAddress.getLoopbackAddress();
      PasswordAuthentication passwordAuthentication0 = Authenticator.requestPasswordAuthentication("k", inetAddress0, 0, "k", "k", "");
      assertNull(passwordAuthentication0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      AuthenticationHandler.GlobalHandler authenticationHandler_GlobalHandler0 = new AuthenticationHandler.GlobalHandler();
      authenticationHandler_GlobalHandler0.remove();
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      AuthenticationHandler authenticationHandler0 = new AuthenticationHandler();
      PasswordAuthentication passwordAuthentication0 = authenticationHandler0.getPasswordAuthentication();
      assertNull(passwordAuthentication0);
  }
}
