/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 01:56:15 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.URL;
import java.nio.charset.Charset;
import java.util.Collection;
import java.util.HashMap;
import java.util.LinkedList;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Set;
import java.util.function.BiConsumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.jsoup.helper.CookieUtil;
import org.jsoup.helper.HttpConnection;
import org.jsoup.nodes.Document;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class CookieUtil_ESTest extends CookieUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response();
      CookieUtil.parseCookie("", httpConnection_Response0);
      assertEquals(400, httpConnection_Response0.statusCode());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response(httpConnection_Request0);
      CookieUtil.parseCookie((String) null, httpConnection_Response0);
      assertNull(httpConnection_Response0.charset());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      URL uRL0 = MockURL.getFileExample();
      HashMap<String, List<String>> hashMap0 = new HashMap<String, List<String>>();
      LinkedList<String> linkedList0 = new LinkedList<String>();
      linkedList0.add("Set-Cookie");
      hashMap0.put("Set-Cookie", linkedList0);
      // Undeclared exception!
      try { 
        CookieUtil.storeCookies(httpConnection_Request0, (HttpConnection.Response) null, uRL0, hashMap0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.helper.CookieUtil", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response(httpConnection_Request0);
      URL uRL0 = MockURL.getHttpExample();
      Map<String, List<String>> map0 = httpConnection_Request0.headers;
      CookieUtil.storeCookies(httpConnection_Request0, httpConnection_Response0, uRL0, map0);
      assertEquals("UTF-8", httpConnection_Request0.postDataCharset());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      URL uRL0 = MockURL.getFileExample();
      HashMap<String, List<String>> hashMap0 = new HashMap<String, List<String>>();
      LinkedList<Locale.LanguageRange> linkedList0 = new LinkedList<Locale.LanguageRange>();
      Document document0 = new Document("N*[6k", "matches");
      Charset charset0 = document0.charset();
      Set<String> set0 = charset0.aliases();
      List<String> list0 = Locale.filterTags((List<Locale.LanguageRange>) linkedList0, (Collection<String>) set0);
      hashMap0.put("Set-Cookie", list0);
      CookieUtil.storeCookies(httpConnection_Request0, (HttpConnection.Response) null, uRL0, hashMap0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      httpConnection_Request0.cookie("UT>z,)NE9", "eof");
      BiConsumer<String, String> biConsumer0 = (BiConsumer<String, String>) mock(BiConsumer.class, new ViolatedAssumptionAnswer());
      CookieUtil.applyCookiesToRequest(httpConnection_Request0, biConsumer0);
      assertNull(httpConnection_Request0.requestBody());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      CookieUtil cookieUtil0 = new CookieUtil();
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      CookieUtil.applyCookiesToRequest(httpConnection_Request0, (BiConsumer<String, String>) null);
      assertEquals(30000, httpConnection_Request0.timeout());
  }
}
