/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 01:58:31 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.io.DataInputStream;
import java.io.File;
import java.io.IOException;
import java.io.InputStream;
import java.io.ObjectOutputStream;
import java.io.PipedInputStream;
import java.io.PushbackInputStream;
import java.io.SequenceInputStream;
import java.nio.ByteBuffer;
import java.nio.charset.Charset;
import java.nio.file.NoSuchFileException;
import java.nio.file.Path;
import java.util.Enumeration;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.io.MockPrintStream;
import org.jsoup.helper.DataUtil;
import org.jsoup.internal.ControllableInputStream;
import org.jsoup.nodes.Document;
import org.jsoup.parser.Parser;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class DataUtil_ESTest extends DataUtil_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      byte[] byteArray0 = new byte[2];
      byteArray0[1] = (byte)4;
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0, (byte)0, (byte)4);
      DataInputStream dataInputStream0 = new DataInputStream(byteArrayInputStream0);
      // Undeclared exception!
      try { 
        DataUtil.load((InputStream) dataInputStream0, "", "");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must set charset arg to character set of file to parse. Set to null to attempt to detect from HTML
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      byteArray0[0] = (byte)10;
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) byteArrayInputStream0, (int) (byte)10);
      Parser parser0 = Parser.xmlParser();
      Document document0 = DataUtil.parseInputStream(controllableInputStream0, (String) null, "", parser0);
      assertEquals(10, controllableInputStream0.max());
      assertEquals("", document0.baseUri());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = DataUtil.mimeBoundary();
      assertEquals("--------------------------------", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = DataUtil.getCharsetFromContentType((String) null);
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      String string0 = DataUtil.getCharsetFromContentType("i32hUcqFDaocJd%");
      assertNull(string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Charset charset0 = Charset.defaultCharset();
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      PushbackInputStream pushbackInputStream0 = new PushbackInputStream(pipedInputStream0);
      DataUtil.CharsetDoc dataUtil_CharsetDoc0 = new DataUtil.CharsetDoc(charset0, (Document) null, pushbackInputStream0);
      Parser parser0 = Parser.htmlParser();
      try { 
        DataUtil.parseInputStream(dataUtil_CharsetDoc0, ".gz", parser0);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) byteArrayInputStream0, (int) (byte)10);
      Parser parser0 = Parser.xmlParser();
      Document document0 = DataUtil.parseInputStream(controllableInputStream0, (String) null, "", parser0);
      assertEquals("", document0.location());
      assertEquals(10, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Enumeration<PushbackInputStream> enumeration0 = (Enumeration<PushbackInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) sequenceInputStream0, (-4319), 28);
      Parser parser0 = Parser.xmlParser();
      // Undeclared exception!
      try { 
        DataUtil.parseInputStream(controllableInputStream0, (String) null, (String) null, parser0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The parameter 'baseUri' must not be null.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 6405, 6405);
      Parser parser0 = Parser.xmlParser();
      Document document0 = DataUtil.parseInputStream(controllableInputStream0, (String) null, "OI@kK;h}XC", parser0);
      assertEquals("OI@kK;h}XC", document0.location());
      assertEquals(6405, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      Document document0 = DataUtil.parseInputStream((ControllableInputStream) null, "--------------------------------", "{|th<F^[:Lz@", parser0);
      assertEquals("{|th<F^[:Lz@", document0.location());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      byte[] byteArray0 = new byte[1];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) byteArrayInputStream0, (int) (byte)10);
      MockPrintStream mockPrintStream0 = new MockPrintStream("http://www.w3.org/XML/1998/namespace");
      ObjectOutputStream objectOutputStream0 = new ObjectOutputStream(mockPrintStream0);
      DataUtil.crossStreams(controllableInputStream0, objectOutputStream0);
      assertTrue(controllableInputStream0.baseReadFully());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      MockFile mockFile0 = new MockFile("version");
      Path path0 = mockFile0.toPath();
      Charset charset0 = Charset.defaultCharset();
      Parser parser0 = Parser.htmlParser();
      try { 
        DataUtil.streamParser(path0, charset0, "version", parser0);
        fail("Expecting exception: NoSuchFileException");
      
      } catch(NoSuchFileException e) {
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      byte[] byteArray0 = new byte[5];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      Document document0 = DataUtil.load((InputStream) byteArrayInputStream0, "UTF-32", "]r~e");
      assertEquals(0, byteArrayInputStream0.available());
      assertEquals("]r~e", document0.location());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream(674);
      try { 
        DataUtil.load((InputStream) pipedInputStream0, "", "", (Parser) null);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      MockFile mockFile0 = new MockFile("$i);rX!I_Az.h{20");
      try { 
        DataUtil.load((File) mockFile0, "$i);rX!I_Az.h{20", "$i);rX!I_Az.h{20");
        fail("Expecting exception: NoSuchFileException");
      
      } catch(NoSuchFileException e) {
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ByteBuffer byteBuffer0 = DataUtil.emptyByteBuffer();
      assertEquals(0, byteBuffer0.remaining());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      try { 
        DataUtil.readToByteBuffer(pipedInputStream0, 704);
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Pipe not connected
         //
         verifyException("java.io.PipedInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      MockFile mockFile0 = new MockFile("Split offset must not be greater than current text length");
      try { 
        DataUtil.load((File) mockFile0, "Split offset must not be greater than current text length", "Split offset must not be greater than current text length", (Parser) null);
        fail("Expecting exception: NoSuchFileException");
      
      } catch(NoSuchFileException e) {
      }
  }
}
