/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:04:04 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.regex.Pattern;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.helper.Regex;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Regex_ESTest extends Regex_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Regex regex0 = Regex.compile("");
      assertEquals("", regex0.toString());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Regex.wantsRe2j(true);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("y`rlAMQ4.D_d9_:");
      Regex regex0 = Regex.fromPattern(pattern0);
      String string0 = regex0.toString();
      assertEquals("y`rlAMQ4.D_d9_:", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      boolean boolean0 = Regex.wantsRe2j();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("org.jsoup.helper.Regex$JdkMatcher");
      Regex regex0 = Regex.fromPattern(pattern0);
      Regex.Matcher regex_Matcher0 = regex0.matcher("org.jsoup.helper.Regex$JdkMatcher");
      boolean boolean0 = regex_Matcher0.find();
      assertFalse(boolean0);
  }
}
