/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:05:32 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.helper.HttpConnection;
import org.jsoup.helper.RequestDispatch;
import org.jsoup.helper.RequestExecutor;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RequestDispatch_ESTest extends RequestDispatch_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response();
      RequestExecutor requestExecutor0 = RequestDispatch.get(httpConnection_Request0, httpConnection_Response0);
      assertNotNull(requestExecutor0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      RequestDispatch requestDispatch0 = new RequestDispatch();
  }
}
