/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:06:08 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.helper.HttpConnection;
import org.jsoup.helper.UrlConnectionExecutor;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class RequestExecutor_ESTest extends RequestExecutor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response();
      UrlConnectionExecutor urlConnectionExecutor0 = new UrlConnectionExecutor((HttpConnection.Request) null, httpConnection_Response0);
  }
}
