/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:07:56 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.net.URL;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.io.MockFile;
import org.evosuite.runtime.mock.java.net.MockURL;
import org.jsoup.helper.HttpConnection;
import org.jsoup.helper.UrlBuilder;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UrlBuilder_ESTest extends UrlBuilder_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      URL uRL0 = MockURL.getFileExample();
      UrlBuilder urlBuilder0 = new UrlBuilder(uRL0);
      StringBuilder stringBuilder0 = new StringBuilder();
      StringBuilder stringBuilder1 = stringBuilder0.appendCodePoint(2715);
      urlBuilder0.q = stringBuilder1;
      URL uRL1 = urlBuilder0.build();
      assertEquals("%E0%AA%9B", uRL1.getQuery());
      assertEquals("some", uRL1.getAuthority());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      UrlBuilder urlBuilder0 = new UrlBuilder(uRL0);
      HttpConnection.KeyVal httpConnection_KeyVal0 = HttpConnection.KeyVal.create("'~|'zS`UyC}~", "");
      urlBuilder0.appendKeyVal(httpConnection_KeyVal0);
      URL uRL1 = urlBuilder0.build();
      assertEquals("http://www.someFakeButWellFormedURL.org/fooExample?%27%7E%7C%27zS%60UyC%7D%7E=", uRL1.toString());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      URL uRL0 = MockURL.getFileExample();
      UrlBuilder urlBuilder0 = new UrlBuilder(uRL0);
      StringBuilder stringBuilder0 = new StringBuilder("~=92T satIj");
      urlBuilder0.q = stringBuilder0;
      URL uRL1 = urlBuilder0.build();
      assertEquals("~=92T+satIj", uRL1.getQuery());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      URL uRL0 = MockURL.getFileExample();
      URL uRL1 = MockURL.URL(uRL0, "> D");
      UrlBuilder urlBuilder0 = new UrlBuilder(uRL1);
      URL uRL2 = urlBuilder0.build();
      assertEquals("some", uRL2.getHost());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      URL uRL0 = MockURL.getHttpExample();
      UrlBuilder urlBuilder0 = new UrlBuilder(uRL0);
      HttpConnection.KeyVal httpConnection_KeyVal0 = HttpConnection.KeyVal.create("'~|'zS`UyC}~", "");
      urlBuilder0.appendKeyVal(httpConnection_KeyVal0);
      urlBuilder0.appendKeyVal(httpConnection_KeyVal0);
      assertEquals("'~|'zS`UyC}~", httpConnection_KeyVal0.key());
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      URL uRL0 = MockURL.getFileExample();
      URL uRL1 = MockURL.URL(uRL0, "ZbZC4#R<NXK-.Qwv1v");
      UrlBuilder urlBuilder0 = new UrlBuilder(uRL1);
      URL uRL2 = urlBuilder0.build();
      assertEquals("R%3CNXK-.Qwv1v", uRL2.getRef());
      assertEquals("some", uRL2.getHost());
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      URL uRL0 = MockURL.getFileExample();
      UrlBuilder urlBuilder0 = new UrlBuilder(uRL0);
      StringBuilder stringBuilder0 = new StringBuilder((CharSequence) ":%s(%2$dn)");
      urlBuilder0.q = stringBuilder0;
      URL uRL1 = urlBuilder0.build();
      assertFalse(uRL1.equals((Object)uRL0));
      assertEquals(":%25s(%252$dn)", uRL1.getQuery());
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      MockFile mockFile0 = new MockFile("?L", "^[a-zA-Z][a-zA-Z0-9+-.]*:");
      URL uRL0 = mockFile0.toURL();
      UrlBuilder urlBuilder0 = new UrlBuilder(uRL0);
      // Undeclared exception!
      try { 
        urlBuilder0.build();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // java.net.URISyntaxException: Expected authority at index 7: file://
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }
}
