/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:09:35 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.IOException;
import java.net.URI;
import java.net.URL;
import java.net.UnknownServiceException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.mock.java.net.MockURI;
import org.jsoup.Connection;
import org.jsoup.helper.HttpConnection;
import org.jsoup.helper.UrlConnectionExecutor;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class UrlConnectionExecutor_ESTest extends UrlConnectionExecutor_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response();
      UrlConnectionExecutor urlConnectionExecutor0 = new UrlConnectionExecutor(httpConnection_Request0, httpConnection_Response0);
      httpConnection_Request0.proxy("org.jsoup.helper.UrlConnectionExecutor", 1);
      // Undeclared exception!
      try { 
        urlConnectionExecutor0.execute();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // URL not set. Make sure to call #url(...) before executing the request.
         //
         verifyException("org.jsoup.helper.HttpConnection$Base", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response(httpConnection_Request0);
      UrlConnectionExecutor urlConnectionExecutor0 = new UrlConnectionExecutor(httpConnection_Request0, httpConnection_Response0);
      // Undeclared exception!
      try { 
        urlConnectionExecutor0.responseBody();
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Not yet executed
         //
         verifyException("org.jsoup.helper.UrlConnectionExecutor", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      URI uRI0 = MockURI.aHttpURI;
      URL uRL0 = MockURI.toURL(uRI0);
      HttpConnection.Request httpConnection_Request1 = (HttpConnection.Request)httpConnection_Request0.url(uRL0);
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response();
      UrlConnectionExecutor urlConnectionExecutor0 = new UrlConnectionExecutor(httpConnection_Request1, httpConnection_Response0);
      Connection.Method connection_Method0 = Connection.Method.DELETE;
      httpConnection_Request0.method = connection_Method0;
      try { 
        urlConnectionExecutor0.execute();
        fail("Expecting exception: UnknownServiceException");
      
      } catch(UnknownServiceException e) {
         //
         // protocol doesn't support output
         //
         verifyException("org.evosuite.runtime.mock.java.net.EvoHttpURLConnection", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      URI uRI0 = MockURI.aHttpURI;
      URL uRL0 = MockURI.toURL(uRI0);
      HttpConnection.Request httpConnection_Request1 = (HttpConnection.Request)httpConnection_Request0.url(uRL0);
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response();
      UrlConnectionExecutor urlConnectionExecutor0 = new UrlConnectionExecutor(httpConnection_Request1, httpConnection_Response0);
      urlConnectionExecutor0.execute();
      try { 
        urlConnectionExecutor0.responseBody();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Could not find: foo.bar
         //
         verifyException("org.evosuite.runtime.mock.java.net.EvoHttpURLConnection", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      HttpConnection.Request httpConnection_Request0 = new HttpConnection.Request();
      HttpConnection.Response httpConnection_Response0 = new HttpConnection.Response();
      UrlConnectionExecutor urlConnectionExecutor0 = new UrlConnectionExecutor(httpConnection_Request0, httpConnection_Response0);
      urlConnectionExecutor0.safeClose();
  }
}
