/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:10:38 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.helper.ValidationException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ValidationException_ESTest extends ValidationException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ValidationException validationException0 = new ValidationException("org.jsoup.helper.ValidationException");
      StackTraceElement[] stackTraceElementArray0 = new StackTraceElement[9];
      StackTraceElement stackTraceElement0 = new StackTraceElement("", "org.jsoup.helper.ValidationException", "j@oYX,~lKp9Q 9sq", 0);
      stackTraceElementArray0[0] = stackTraceElement0;
      stackTraceElementArray0[1] = stackTraceElementArray0[0];
      stackTraceElementArray0[2] = stackTraceElementArray0[0];
      StackTraceElement stackTraceElement1 = new StackTraceElement("org.jsoup.helper.Validate", "dxFoUssY5Bat^#'tH", (String) null, 0);
      stackTraceElementArray0[3] = stackTraceElement1;
      stackTraceElementArray0[4] = stackTraceElement1;
      stackTraceElementArray0[5] = stackTraceElementArray0[0];
      stackTraceElementArray0[6] = stackTraceElement0;
      stackTraceElementArray0[7] = stackTraceElementArray0[0];
      stackTraceElementArray0[8] = stackTraceElement1;
      validationException0.setStackTrace(stackTraceElementArray0);
      Throwable throwable0 = validationException0.fillInStackTrace();
      assertSame(validationException0, throwable0);
  }
}
