/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:12:53 GMT 2026
 */

package org.jsoup.helper;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import com.sun.org.apache.xerces.internal.dom.DocumentImpl;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.helper.W3CDom;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.parser.Parser;
import org.jsoup.parser.Tag;
import org.junit.runner.RunWith;
import org.w3c.dom.DOMException;
import org.w3c.dom.NodeList;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class W3CDom_ESTest extends W3CDom_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Tag tag0 = new Tag("jsoup");
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.put("javax.xml.xpath.XPathFactory:jsoup", "DQbE:[>ZD=doW");
      Element element0 = new Element(tag0, "", attributes1);
      Document document0 = new Document("jsoupSource");
      document0.prependChild(element0);
      w3CDom0.fromJsoup((Element) document0);
      assertTrue(w3CDom0.namespaceAware());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Tag tag0 = new Tag("jsoup");
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("jsoup", "DQbE:[>ZD=doWh");
      Attributes attributes1 = attributes0.put(attribute0);
      Element element0 = new Element(tag0, "", attributes1);
      w3CDom0.fromJsoup(element0);
      assertTrue(w3CDom0.namespaceAware());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      assertTrue(w3CDom0.namespaceAware());
      
      Tag tag0 = new Tag("jsoup");
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("jsoup", "DQbE:[>ZD=doWh");
      Attributes attributes1 = attributes0.put(attribute0);
      Element element0 = new Element(tag0, "", attributes1);
      W3CDom w3CDom1 = w3CDom0.namespaceAware(false);
      w3CDom1.fromJsoup(element0);
      assertFalse(w3CDom0.namespaceAware());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Tag tag0 = Tag.valueOf("javax.xml.xpath.XPathFactory:jsoup");
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.add("javax.xml.xpath.XPathFactory:jsoup", "kzP(Niva{Le");
      Element element0 = new Element(tag0, "html", attributes1);
      Document document0 = Parser.parseBodyFragment("bK|PR/>", "jsoupSource");
      org.w3c.dom.Document document1 = W3CDom.convert(document0);
      // Undeclared exception!
      try { 
        w3CDom0.convert(element0, document1);
        fail("Expecting exception: DOMException");
      
      } catch(DOMException e) {
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Document document0 = Parser.parse("I4Ey", "T/|e$.;)'t)(&6)");
      org.w3c.dom.Document document1 = w3CDom0.fromJsoup((Element) document0);
      W3CDom.W3CBuilder w3CDom_W3CBuilder0 = new W3CDom.W3CBuilder(document1);
      DataNode dataNode0 = new DataNode("Z~BhIIu");
      // Undeclared exception!
      try { 
        w3CDom_W3CBuilder0.head(dataNode0, 1542);
        fail("Expecting exception: DOMException");
      
      } catch(DOMException e) {
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      assertTrue(w3CDom0.namespaceAware());
      
      w3CDom0.namespaceAware(false);
      Document document0 = Parser.parse("javax.xml.xpath.XPathFactory:jsoup", "horX");
      document0.prependElement("javax.xml.xpath.XPathFactory:jsoup", "jsoupSource");
      w3CDom0.fromJsoup((Element) document0);
      assertFalse(w3CDom0.namespaceAware());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Document document0 = Parser.parse("javax.xml.xpath.XPathFactory:jsoup", "horX");
      DocumentImpl documentImpl0 = (DocumentImpl)w3CDom0.fromJsoup((Element) document0);
      Class<Document> class0 = Document.class;
      List<Document> list0 = w3CDom0.sourceNodes((NodeList) documentImpl0, class0);
      assertTrue(w3CDom0.namespaceAware());
      assertFalse(list0.contains(document0));
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Document document0 = Parser.parseBodyFragment("javax.xml.xpath.XPathFactory:jsoup", "javax.xml.xpath.XPathFactory:jsoup");
      Element element0 = document0.html("javax.xml.xpath.XPathFactory:jsoup");
      // Undeclared exception!
      try { 
        w3CDom0.fromJsoup(element0);
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Document document0 = Parser.parseBodyFragment("javax.xml.xpath.XPathFactory:jsoup", "javax.xml.xpath.XPathFactory:jsoup");
      org.w3c.dom.Document document1 = w3CDom0.fromJsoup(document0);
      String string0 = w3CDom0.asString(document1);
      assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\"?><html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body>javax.xml.xpath.XPathFactory:jsoup</body></html>", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Document document0 = Parser.parse("javax.xml.xpath.XPathFactory:jsoup", "horX");
      org.w3c.dom.Document document1 = w3CDom0.fromJsoup((Element) document0);
      Map<String, String> map0 = document0.dataset();
      String string0 = W3CDom.asString(document1, map0);
      assertEquals("<?xml version=\"1.0\" encoding=\"UTF-8\"?><html xmlns=\"http://www.w3.org/1999/xhtml\"><head/><body>javax.xml.xpath.XPathFactory:jsoup</body></html>", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      HashMap<String, String> hashMap0 = W3CDom.OutputHtml();
      assertEquals(1, hashMap0.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      boolean boolean0 = w3CDom0.namespaceAware();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Document document0 = Document.createShell("jsoupSource");
      org.w3c.dom.Document document1 = w3CDom0.fromJsoup((Element) document0);
      // Undeclared exception!
      try { 
        w3CDom0.convert(document0, document1);
        fail("Expecting exception: DOMException");
      
      } catch(DOMException e) {
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      HashMap<String, String> hashMap0 = W3CDom.OutputXml();
      assertFalse(hashMap0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      W3CDom w3CDom0 = new W3CDom();
      Document document0 = Parser.parseBodyFragment("javax.xml.xpath.XPathFactory:jsoup", "");
      org.w3c.dom.Document document1 = W3CDom.convert(document0);
      w3CDom0.selectXpath("jsoupSource", document1);
      assertTrue(w3CDom0.namespaceAware());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Document document0 = Parser.parse("javax.xml.xpath.XPathFactory:jsoup", "horX");
      Class<Document> class0 = Document.class;
      document0.selectXpath("strong", class0);
  }
}
