/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:32:42 GMT 2026
 */

package org.jsoup.select;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Comment;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.parser.Parser;
import org.jsoup.select.Collector;
import org.jsoup.select.CombiningEvaluator;
import org.jsoup.select.Evaluator;
import org.jsoup.select.Nodes;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Collector_ESTest extends Collector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Evaluator.IsOnlyOfType evaluator_IsOnlyOfType0 = new Evaluator.IsOnlyOfType();
      Document document0 = new Document("Uz~\"", "Uz~\"");
      Element element0 = Collector.findFirst(evaluator_IsOnlyOfType0, document0);
      assertNull(element0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Evaluator.ContainsData evaluator_ContainsData0 = new Evaluator.ContainsData("k'J0H6SC&");
      Document document0 = Parser.parseBodyFragment("", "kp");
      Class<Comment> class0 = Comment.class;
      Nodes<Comment> nodes0 = Collector.collectNodes((Evaluator) evaluator_ContainsData0, (Element) document0, class0);
      assertTrue(nodes0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Document document0 = Document.createShell("HvKQT?xl#;=A`|-");
      document0.getElementsMatchingOwnText(",%~E-");
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Evaluator.IsEmpty evaluator_IsEmpty0 = new Evaluator.IsEmpty();
      Element element0 = new Element(")*V;LTO]a3neUL`7~", "bdo");
      Class<CDataNode> class0 = CDataNode.class;
      CDataNode cDataNode0 = Collector.findFirstNode((Evaluator) evaluator_IsEmpty0, element0, class0);
      assertNull(cDataNode0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      CombiningEvaluator.Or combiningEvaluator_Or0 = new CombiningEvaluator.Or();
      combiningEvaluator_Or0.wantsNodes = true;
      // Undeclared exception!
      try { 
        Collector.collect(combiningEvaluator_Or0, (Element) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Collector", e);
      }
  }
}
