/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:37:16 GMT 2026
 */

package org.jsoup.select;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.List;
import java.util.regex.Pattern;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jsoup.nodes.Comment;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.FormElement;
import org.jsoup.nodes.TextNode;
import org.jsoup.parser.Parser;
import org.jsoup.select.Elements;
import org.jsoup.select.Evaluator;
import org.jsoup.select.NodeFilter;
import org.jsoup.select.NodeVisitor;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Elements_ESTest extends Elements_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      Document document0 = parser0.parseInput("http://www.w3.org/1999/xhtml", "http://www.w3.org/2000/svg");
      Elements elements0 = document0.getElementsByAttribute("http://www.w3.org/1998/Math/MathML");
      elements0.add(0, (Element) document0);
      Elements elements1 = elements0.append("=e");
      List<TextNode> list0 = elements1.textNodes();
      assertFalse(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("0@)ol!", "");
      Elements elements0 = document0.getElementsMatchingText("o");
      List<FormElement> list0 = elements0.forms();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("org.jsoup.select.Elements");
      Elements elements1 = elements0.parents();
      assertEquals(1, elements1.size());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("org.jsoup.select.Elements");
      Elements elements1 = elements0.prevAll();
      assertEquals(1, elements1.size());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Document document0 = Document.createShell("(Hx[L,g6ncD");
      Evaluator.IsLastOfType evaluator_IsLastOfType0 = new Evaluator.IsLastOfType();
      Elements elements0 = document0.select((Evaluator) evaluator_IsLastOfType0);
      boolean boolean0 = elements0.is("G3i5");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      Document document0 = parser0.parseInput("http://www.w3.org/1999/xhtml", "http://www.w3.org/2000/svg");
      Elements elements0 = document0.getElementsByAttribute("http://www.w3.org/1998/Math/MathML");
      elements0.add(0, (Element) document0);
      Elements elements1 = elements0.eq(0);
      assertEquals(1, elements1.size());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Document document0 = Document.createShell("");
      Elements elements0 = document0.parents();
      Elements elements1 = elements0.eq(0);
      assertTrue(elements1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Document document0 = Parser.parse("S", "-'Vd");
      Elements elements0 = document0.children();
      Elements elements1 = elements0.empty();
      assertSame(elements1, elements0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Document document0 = Document.createShell("");
      Pattern pattern0 = Pattern.compile("");
      Elements elements0 = document0.getElementsMatchingOwnText(pattern0);
      // Undeclared exception!
      try { 
        elements0.unwrap();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Document document0 = new Document("AoU]|3J?5", "AoU]|3J?5");
      Elements elements0 = document0.getElementsByAttributeValueMatching("AoU]|3J?5", "B%0cOQ /");
      Elements elements1 = elements0.unwrap();
      assertSame(elements1, elements0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("0@)ol!", "");
      Elements elements0 = document0.getElementsMatchingText("o");
      Elements elements1 = elements0.prepend("*H%s");
      assertEquals(3, elements1.size());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Document document0 = Document.createShell("(Hx[L,g6ncD");
      Evaluator.IsLastOfType evaluator_IsLastOfType0 = new Evaluator.IsLastOfType();
      Elements elements0 = document0.select((Evaluator) evaluator_IsLastOfType0);
      Elements elements1 = elements0.html("c)HrzAo=P-");
      assertFalse(elements1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Document document0 = Document.createShell("");
      Pattern pattern0 = Pattern.compile("");
      Elements elements0 = document0.getElementsMatchingOwnText(pattern0);
      // Undeclared exception!
      try { 
        elements0.tagName("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The 'tagName' parameter must not be empty.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Elements elements0 = new Elements();
      Elements elements1 = elements0.tagName("uWA wO");
      assertEquals(0, elements1.size());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      Document document0 = parser0.parseInput("http://www.w3.org/1999/xhtml", "http://www.w3.org/2000/svg");
      Elements elements0 = document0.getElementsByAttribute("http://www.w3.org/1998/Math/MathML");
      elements0.add(0, (Element) document0);
      List<String> list0 = elements0.eachText();
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Element element0 = new Element("u+KGTa249CoaJ");
      Elements elements0 = element0.getElementsByTag("u+KGTa249CoaJ");
      List<String> list0 = elements0.eachText();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Document document0 = Parser.parse("\n", "\n");
      Element element0 = document0.text("zR9kQxSuTN");
      Pattern pattern0 = Pattern.compile("zR9kQxSuTN", 5109);
      Elements elements0 = element0.getElementsMatchingText(pattern0);
      boolean boolean0 = elements0.hasText();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("", "");
      Pattern pattern0 = Pattern.compile("");
      Elements elements0 = document0.getElementsMatchingOwnText(pattern0);
      boolean boolean0 = elements0.hasText();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("org.jsoup.select.Elements");
      Elements elements1 = elements0.val("org.jsoup.select.Elements");
      assertSame(elements0, elements1);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("0@)ol!", "");
      Elements elements0 = document0.getElementsMatchingText("o");
      String string0 = elements0.val();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("");
      Elements elements1 = elements0.prev("org.jsoup.select.Elements");
      elements1.val();
      assertTrue(elements1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("0@)ol!", "");
      Elements elements0 = document0.getElementsMatchingText("o");
      boolean boolean0 = elements0.hasClass("Must run parse() before alling.");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("org.jsoup.select.Elements");
      Elements elements1 = elements0.toggleClass("REMOVE");
      assertEquals(3, elements1.size());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("org.jsoup.nodes.LeafNode", "org.jsoup.nodes.LeafNode");
      Elements elements0 = document0.children();
      Elements elements1 = elements0.removeClass("http://www.w3.org/XML/1998/namespace");
      assertEquals(1, elements1.size());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("org.jsoup.select.Elements");
      Elements elements1 = elements0.addClass("org.jsoup.select.Elements");
      assertFalse(elements1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("0@)ol!", "");
      Elements elements0 = document0.getElementsMatchingText("o");
      Elements elements1 = elements0.removeAttr("");
      assertSame(elements0, elements1);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("0@)ol!", "");
      Elements elements0 = document0.getElementsMatchingText("o");
      Elements elements1 = elements0.attr("", "o");
      assertFalse(elements1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("0@)ol!", "");
      Elements elements0 = document0.getElementsMatchingText("o");
      List<String> list0 = elements0.eachAttr("*H%s");
      assertFalse(list0.contains(""));
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("0@)ol!", "");
      Elements elements0 = document0.getElementsMatchingText("o");
      boolean boolean0 = elements0.hasAttr("lrsI9<k*h3.");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("0@)ol!", "");
      Elements elements0 = document0.getElementsMatchingText("o");
      String string0 = elements0.attr("Must run parse() before alling.");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("");
      Elements elements1 = elements0.clone();
      assertNotSame(elements1, elements0);
      assertFalse(elements1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Document document0 = new Document("AoU]|3J?5", "AoU]|3J?5");
      Elements elements0 = document0.getElementsByAttributeValueMatching("AoU]|3J?5", "B%0cOQ /");
      Elements elements1 = elements0.next();
      assertNotSame(elements1, elements0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Elements elements0 = new Elements();
      Elements elements1 = elements0.before("");
      assertSame(elements0, elements1);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("org.jsoup.select.Elements");
      // Undeclared exception!
      try { 
        elements0.set(0, (Element) document0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("org.jsoup.select.Elements");
      Elements elements1 = elements0.select("org.jsoup.select.Elements");
      assertTrue(elements1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Document document0 = Document.createShell("");
      Elements elements0 = document0.parents();
      NodeFilter nodeFilter0 = mock(NodeFilter.class, new ViolatedAssumptionAnswer());
      Elements elements1 = elements0.filter(nodeFilter0);
      assertTrue(elements1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Document document0 = Document.createShell("(Hx[L,g6ncD");
      Evaluator.IsLastOfType evaluator_IsLastOfType0 = new Evaluator.IsLastOfType();
      Elements elements0 = document0.select((Evaluator) evaluator_IsLastOfType0);
      Elements elements1 = elements0.prev();
      assertEquals(1, elements1.size());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Elements elements0 = new Elements();
      ArrayList<Element> arrayList0 = elements0.asList();
      assertEquals(0, arrayList0.size());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Document document0 = new Document("");
      Elements elements0 = document0.getElementsByTag("org.jsoup.select.Evaluator$ContainsData");
      // Undeclared exception!
      try { 
        elements0.deselect(0);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 0, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Elements elements0 = new Elements();
      Elements elements1 = elements0.after("~");
      assertTrue(elements1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Document document0 = new Document("OAkE`<=h0AnU", "|vI'M2YBUrK");
      Elements elements0 = document0.getElementsByAttribute("|vI'M2YBUrK");
      // Undeclared exception!
      try { 
        elements0.expectFirst("|vI'M2YBUrK");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Could not parse query '|vI'M2YBUrK': unexpected token at '|vI'M2YBUrK'
         //
         verifyException("org.jsoup.select.QueryParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("q-#5=9<[ZNMGGcU", "q-#5=9<[ZNMGGcU");
      Elements elements0 = document0.siblingElements();
      String string0 = elements0.text();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Document document0 = Document.createShell("(Hx[L,g6ncD");
      Evaluator.IsLastOfType evaluator_IsLastOfType0 = new Evaluator.IsLastOfType();
      Elements elements0 = document0.select((Evaluator) evaluator_IsLastOfType0);
      Elements elements1 = elements0.remove();
      assertSame(elements0, elements1);
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("org.jsoup.select.Elements");
      List<Comment> list0 = elements0.comments();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("org.jsoup.select.Elements");
      Elements elements1 = elements0.not("org.jsoup.select.Elements");
      assertEquals(3, elements1.size());
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Elements elements0 = new Elements(2536);
      Element element0 = elements0.last();
      assertNull(element0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Document document0 = Parser.parse("org.jsoup.select.Elements", "org.jsoup.select.Elements");
      Elements elements0 = document0.getElementsContainingText("org.jsoup.select.Elements");
      NodeVisitor nodeVisitor0 = mock(NodeVisitor.class, new ViolatedAssumptionAnswer());
      Elements elements1 = elements0.traverse(nodeVisitor0);
      assertEquals(3, elements1.size());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("0@)ol!", "");
      Elements elements0 = document0.getElementsMatchingText("o");
      String string0 = elements0.html();
      assertEquals("<html>\n <head></head>\n <body>0@)ol!</body>\n</html>\n<head></head>\n<body>0@)ol!</body>\n0@)ol!", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Document document0 = Parser.parse("0@.#BYI", "0@.#BYI");
      Pattern pattern0 = Pattern.compile("0@.#BYI", (-907685685));
      Elements elements0 = document0.getElementsMatchingText(pattern0);
      Elements elements1 = elements0.nextAll();
      assertTrue(elements1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("q-#5=9<[ZNMGGcU", "q-#5=9<[ZNMGGcU");
      Elements elements0 = document0.siblingElements();
      // Undeclared exception!
      try { 
        elements0.selectFirst("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // String must not be empty
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Document document0 = Document.createShell("");
      Elements elements0 = document0.parents();
      List<DataNode> list0 = elements0.dataNodes();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Elements elements0 = new Elements();
      Elements elements1 = elements0.prevAll("quirks");
      assertNotSame(elements1, elements0);
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Elements elements0 = new Elements();
      Elements elements1 = elements0.wrap("~");
      assertEquals(0, elements1.size());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Document document0 = new Document("OAkE`<=h0AnU", "|vI'M2YBUrK");
      Elements elements0 = document0.getElementsByAttribute("|vI'M2YBUrK");
      Elements elements1 = elements0.next("h6");
      assertNotSame(elements1, elements0);
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Document document0 = Parser.parse("S", "-'Vd");
      Elements elements0 = document0.children();
      elements0.nextAll("S");
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      Elements elements0 = new Elements();
      // Undeclared exception!
      try { 
        elements0.remove(3948);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 3948, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }
}
