/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:43:10 GMT 2026
 */

package org.jsoup.select;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import java.util.function.Predicate;
import java.util.function.UnaryOperator;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Comment;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.DocumentType;
import org.jsoup.nodes.TextNode;
import org.jsoup.nodes.XmlDeclaration;
import org.jsoup.parser.Parser;
import org.jsoup.select.Elements;
import org.jsoup.select.Evaluator;
import org.jsoup.select.Nodes;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Nodes_ESTest extends Nodes_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Comment[] commentArray0 = new Comment[8];
      Nodes<Comment> nodes0 = new Nodes<Comment>(commentArray0);
      UnaryOperator<Comment> unaryOperator0 = UnaryOperator.identity();
      // Undeclared exception!
      try { 
        nodes0.replaceAll(unaryOperator0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("", "gR1ehO!A%rh6PB>~Y");
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      Class<CDataNode> class0 = CDataNode.class;
      Nodes<CDataNode> nodes0 = document0.selectNodes((Evaluator) evaluator_IsLastChild0, class0);
      UnaryOperator<CDataNode> unaryOperator0 = UnaryOperator.identity();
      nodes0.replaceAll(unaryOperator0);
      assertTrue(nodes0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TextNode[] textNodeArray0 = new TextNode[6];
      TextNode textNode0 = new TextNode("Z(vkIx7X+M^0");
      textNodeArray0[0] = textNode0;
      Nodes<TextNode> nodes0 = new Nodes<TextNode>(textNodeArray0);
      Predicate<Object> predicate0 = Predicate.isEqual((Object) null);
      // Undeclared exception!
      try { 
        nodes0.removeIf(predicate0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Nodes", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Nodes<Comment> nodes0 = new Nodes<Comment>();
      Predicate<Comment> predicate0 = Predicate.isEqual((Object) "");
      boolean boolean0 = nodes0.removeIf(predicate0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Comment[] commentArray0 = new Comment[1];
      Nodes<Comment> nodes0 = new Nodes<Comment>(commentArray0);
      boolean boolean0 = nodes0.retainAll(nodes0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Document document0 = Parser.parse("n{5]", "CSS identifier expected, but end of input found");
      List<TextNode> list0 = document0.textNodes();
      Nodes<TextNode> nodes0 = new Nodes<TextNode>(list0);
      DataNode[] dataNodeArray0 = new DataNode[6];
      Nodes<DataNode> nodes1 = new Nodes<DataNode>(dataNodeArray0);
      // Undeclared exception!
      try { 
        nodes1.retainAll(nodes0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Nodes", e);
      }
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Nodes<XmlDeclaration> nodes0 = new Nodes<XmlDeclaration>(0);
      boolean boolean0 = nodes0.retainAll(nodes0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Comment[] commentArray0 = new Comment[6];
      Nodes<Comment> nodes0 = new Nodes<Comment>(commentArray0);
      // Undeclared exception!
      try { 
        nodes0.removeAll(nodes0);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Nodes", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Nodes<Comment> nodes0 = new Nodes<Comment>();
      Comment comment0 = nodes0.last();
      assertNull(comment0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Comment[] commentArray0 = new Comment[1];
      Nodes<Comment> nodes0 = new Nodes<Comment>(commentArray0);
      Comment comment0 = nodes0.last();
      assertNull(comment0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Nodes<DocumentType> nodes0 = new Nodes<DocumentType>();
      DocumentType documentType0 = nodes0.first();
      assertNull(documentType0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Comment[] commentArray0 = new Comment[1];
      Nodes<Comment> nodes0 = new Nodes<Comment>(commentArray0);
      Comment comment0 = nodes0.first();
      assertNull(comment0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TextNode[] textNodeArray0 = new TextNode[6];
      Nodes<TextNode> nodes0 = new Nodes<TextNode>(textNodeArray0);
      // Undeclared exception!
      try { 
        nodes0.wrap("/4[@");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Nodes", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Nodes<XmlDeclaration> nodes0 = new Nodes<XmlDeclaration>();
      Nodes<XmlDeclaration> nodes1 = nodes0.wrap("CY[\"N_4Pbx.&ok|?L");
      assertTrue(nodes1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      DataNode[] dataNodeArray0 = new DataNode[7];
      Nodes<DataNode> nodes0 = new Nodes<DataNode>(dataNodeArray0);
      // Undeclared exception!
      try { 
        nodes0.after("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Nodes", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Nodes<Comment> nodes0 = new Nodes<Comment>();
      Nodes<Comment> nodes1 = nodes0.after("");
      assertSame(nodes1, nodes0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      CDataNode[] cDataNodeArray0 = new CDataNode[5];
      Nodes<CDataNode> nodes0 = new Nodes<CDataNode>(cDataNodeArray0);
      // Undeclared exception!
      try { 
        nodes0.before("");
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Nodes", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("", "gR1ehO!A%rh6PB>~Y");
      Evaluator.IsLastChild evaluator_IsLastChild0 = new Evaluator.IsLastChild();
      Class<CDataNode> class0 = CDataNode.class;
      Nodes<CDataNode> nodes0 = document0.selectNodes((Evaluator) evaluator_IsLastChild0, class0);
      Nodes<CDataNode> nodes1 = nodes0.before(".&FG<~");
      assertSame(nodes0, nodes1);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Comment[] commentArray0 = new Comment[1];
      Nodes<Comment> nodes0 = new Nodes<Comment>(commentArray0);
      // Undeclared exception!
      try { 
        nodes0.remove();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.select.Nodes", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Comment[] commentArray0 = new Comment[1];
      Comment comment0 = new Comment("u,hY9vTnCd3,Pp-s'_U");
      commentArray0[0] = comment0;
      Nodes<Comment> nodes0 = new Nodes<Comment>(commentArray0);
      Nodes<Comment> nodes1 = nodes0.clone();
      assertFalse(nodes1.contains(comment0));
      
      boolean boolean0 = nodes1.removeAll(nodes0);
      assertFalse(boolean0);
      assertFalse(nodes1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Nodes<XmlDeclaration> nodes0 = new Nodes<XmlDeclaration>();
      ArrayList<XmlDeclaration> arrayList0 = nodes0.asList();
      assertTrue(arrayList0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Nodes<DataNode> nodes0 = new Nodes<DataNode>(0);
      nodes0.clear();
      assertEquals(0, nodes0.size());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Nodes<DataNode> nodes0 = new Nodes<DataNode>(0);
      Nodes<DataNode> nodes1 = new Nodes<DataNode>((Collection<DataNode>) nodes0);
      assertTrue(nodes1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Nodes<TextNode> nodes0 = new Nodes<TextNode>();
      String string0 = nodes0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Comment[] commentArray0 = new Comment[1];
      Comment comment0 = new Comment("u,hY9vTnCd3,Pp-s'_U");
      Nodes<Comment> nodes0 = new Nodes<Comment>(commentArray0);
      boolean boolean0 = nodes0.deselect((Object) comment0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Nodes<DocumentType> nodes0 = new Nodes<DocumentType>(44);
      // Undeclared exception!
      try { 
        nodes0.deselect(44);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Index: 44, Size: 0
         //
         verifyException("java.util.ArrayList", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("", "");
      Elements elements0 = document0.getElementsByIndexEquals(0);
      elements0.deselectAll();
  }
}
