/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:41:18 GMT 2026
 */

package org.jsoup.select;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.regex.Pattern;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.helper.Regex;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.select.NodeEvaluator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NodeEvaluator_ESTest extends NodeEvaluator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Class<Node> class0 = Node.class;
      NodeEvaluator.InstanceType nodeEvaluator_InstanceType0 = new NodeEvaluator.InstanceType(class0, "");
      String string0 = nodeEvaluator_InstanceType0.toString();
      assertEquals("::", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Class<Node> class0 = Node.class;
      NodeEvaluator.InstanceType nodeEvaluator_InstanceType0 = new NodeEvaluator.InstanceType(class0, "");
      int int0 = nodeEvaluator_InstanceType0.cost();
      assertEquals(1, int0);
      assertEquals("::", nodeEvaluator_InstanceType0.toString());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      NodeEvaluator.ContainsValue nodeEvaluator_ContainsValue0 = new NodeEvaluator.ContainsValue("");
      String string0 = nodeEvaluator_ContainsValue0.toString();
      assertEquals(":contains()", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      NodeEvaluator.ContainsValue nodeEvaluator_ContainsValue0 = new NodeEvaluator.ContainsValue("");
      int int0 = nodeEvaluator_ContainsValue0.cost();
      assertEquals(6, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("I c1*OEx");
      Regex regex0 = Regex.fromPattern(pattern0);
      NodeEvaluator.MatchesValue nodeEvaluator_MatchesValue0 = new NodeEvaluator.MatchesValue(regex0);
      String string0 = nodeEvaluator_MatchesValue0.toString();
      assertEquals(":matches(I c1*OEx)", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("I c1*OEx");
      Regex regex0 = Regex.fromPattern(pattern0);
      NodeEvaluator.MatchesValue nodeEvaluator_MatchesValue0 = new NodeEvaluator.MatchesValue(regex0);
      int int0 = nodeEvaluator_MatchesValue0.cost();
      assertEquals(8, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("I c1*OEx");
      Regex regex0 = Regex.fromPattern(pattern0);
      NodeEvaluator.MatchesValue nodeEvaluator_MatchesValue0 = new NodeEvaluator.MatchesValue(regex0);
      Document document0 = Document.createShell(":u{mfD+$z|:j2B@+");
      boolean boolean0 = nodeEvaluator_MatchesValue0.evaluateMatch(document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      NodeEvaluator.BlankValue nodeEvaluator_BlankValue0 = new NodeEvaluator.BlankValue();
      int int0 = nodeEvaluator_BlankValue0.cost();
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      NodeEvaluator.BlankValue nodeEvaluator_BlankValue0 = new NodeEvaluator.BlankValue();
      String string0 = nodeEvaluator_BlankValue0.toString();
      assertEquals(":blank", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      NodeEvaluator.BlankValue nodeEvaluator_BlankValue0 = new NodeEvaluator.BlankValue();
      CDataNode cDataNode0 = new CDataNode("foreignObject");
      boolean boolean0 = nodeEvaluator_BlankValue0.evaluateMatch(cDataNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      NodeEvaluator.ContainsValue nodeEvaluator_ContainsValue0 = new NodeEvaluator.ContainsValue("nth-last-child");
      CDataNode cDataNode0 = new CDataNode("nth-last-child");
      boolean boolean0 = nodeEvaluator_ContainsValue0.matches((Element) null, (Node) cDataNode0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Class<Node> class0 = Node.class;
      NodeEvaluator.InstanceType nodeEvaluator_InstanceType0 = new NodeEvaluator.InstanceType(class0, "");
      Document document0 = Document.createShell(":u{mfD+$z|:j2B@+");
      nodeEvaluator_InstanceType0.matches(document0, document0);
  }
}
