/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:49:31 GMT 2026
 */

package org.jsoup.select;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.parser.Parser;
import org.jsoup.select.Elements;
import org.jsoup.select.Evaluator;
import org.jsoup.select.Selector;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Selector_ESTest extends Selector_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      // Undeclared exception!
      try { 
        Selector.unescapeCssIdentifier("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CSS identifier expected, but end of input found
         //
         verifyException("org.jsoup.parser.TokenQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = Selector.unescapeCssIdentifier("q");
      assertEquals("q", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Document document0 = new Document("<\"7m]I)HG+>*r`p");
      Element element0 = Selector.selectFirst("*", (Iterable<Element>) document0);
      assertSame(element0, document0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Document document0 = new Document("q", "q");
      Element element0 = Selector.selectFirst("q", (Iterable<Element>) document0);
      assertNull(element0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Document document0 = Parser.parse(":", "");
      Elements elements0 = document0.getElementsByAttributeValueNot(":", ":");
      Elements elements1 = Selector.filterOut(elements0, elements0);
      assertEquals(0, elements1.size());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Document document0 = new Document("B3u]eOwzxqa=,@~h;h");
      Element element0 = document0.body();
      Elements elements0 = element0.parents();
      Elements elements1 = Selector.filterOut(elements0, elements0);
      Elements elements2 = Selector.filterOut(elements0, elements1);
      assertFalse(elements2.equals((Object)elements1));
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Selector.SelectorParseException selector_SelectorParseException0 = new Selector.SelectorParseException("");
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("M n2xB**&{-", "M n2xB**&{-");
      // Undeclared exception!
      try { 
        Selector.select("http://www.w3.org/1998/Math/MathML", (Iterable<Element>) document0);
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Could not parse query 'http://www.w3.org/1998/Math/MathML': unexpected token at '//www.w3.org/1998/Math/MathML'
         //
         verifyException("org.jsoup.select.QueryParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Object[] objectArray0 = new Object[0];
      Selector.SelectorParseException selector_SelectorParseException0 = new Selector.SelectorParseException((Throwable) null, "org.jsoup.helper.RequestExecutor", objectArray0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Document document0 = new Document("");
      // Undeclared exception!
      try { 
        Selector.selectFirst("", (Element) document0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // String must not be empty
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Evaluator.IsRoot evaluator_IsRoot0 = new Evaluator.IsRoot();
      // Undeclared exception!
      try { 
        Selector.select((Evaluator) evaluator_IsRoot0, (Element) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Document document0 = new Document("", "");
      Selector.selectStream("QN", (Element) document0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      // Undeclared exception!
      try { 
        Selector.select("", (Element) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // String must not be empty
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      String string0 = Selector.escapeCssIdentifier("http://www.w3.org/1998/Math/MathML");
      assertEquals("http\\:\\/\\/www\\.w3\\.org\\/1998\\/Math\\/MathML", string0);
  }
}
