/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:51:59 GMT 2026
 */

package org.jsoup.select;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.Reader;
import java.io.StringReader;
import java.util.LinkedList;
import java.util.regex.Pattern;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.helper.Regex;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.parser.Parser;
import org.jsoup.select.CombiningEvaluator;
import org.jsoup.select.Evaluator;
import org.jsoup.select.StructuralEvaluator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StructuralEvaluator_ESTest extends StructuralEvaluator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Evaluator.IndexGreaterThan evaluator_IndexGreaterThan0 = new Evaluator.IndexGreaterThan(19);
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_IndexGreaterThan0);
      structuralEvaluator_PreviousSibling0.wantsNodes = true;
      Document document0 = new Document("", ":gt(19)");
      CDataNode cDataNode0 = new CDataNode("source");
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(structuralEvaluator_PreviousSibling0);
      boolean boolean0 = structuralEvaluator_ImmediatePreviousSibling0.matches((Element) document0, (Node) cDataNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Evaluator.AllElements evaluator_AllElements0 = new Evaluator.AllElements();
      StructuralEvaluator.Is structuralEvaluator_Is0 = new StructuralEvaluator.Is(evaluator_AllElements0);
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(structuralEvaluator_Is0);
      Document document0 = Document.createShell("xV~~4g/}{e(aT;");
      boolean boolean0 = structuralEvaluator_ImmediatePreviousSibling0.evaluateMatch(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      StructuralEvaluator.Is structuralEvaluator_Is0 = new StructuralEvaluator.Is(structuralEvaluator_Root0);
      Document document0 = Document.createShell("FH6_Po5wifQ");
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(structuralEvaluator_Is0);
      boolean boolean0 = structuralEvaluator_PreviousSibling0.matches((Element) document0, (Node) document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Evaluator.Tag evaluator_Tag0 = new Evaluator.Tag("Rawtext");
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_Tag0);
      StructuralEvaluator.ImmediateParentRun structuralEvaluator_ImmediateParentRun0 = new StructuralEvaluator.ImmediateParentRun(structuralEvaluator_Has0);
      structuralEvaluator_ImmediateParentRun0.reset();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("");
      Evaluator.MatchesWholeText evaluator_MatchesWholeText0 = new Evaluator.MatchesWholeText(pattern0);
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(evaluator_MatchesWholeText0);
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(structuralEvaluator_PreviousSibling0);
      StructuralEvaluator.ImmediateParentRun structuralEvaluator_ImmediateParentRun0 = new StructuralEvaluator.ImmediateParentRun(structuralEvaluator_ImmediatePreviousSibling0);
      Parser parser0 = Parser.htmlParser();
      Document document0 = parser0.parseInput("", "");
      boolean boolean0 = structuralEvaluator_ImmediateParentRun0.evaluateMatch(document0, (Node) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      LinkedList<Evaluator> linkedList0 = new LinkedList<Evaluator>();
      CombiningEvaluator.Or combiningEvaluator_Or0 = new CombiningEvaluator.Or(linkedList0);
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(combiningEvaluator_Or0);
      Document document0 = Parser.parseBodyFragment(":not(%s)", "#S");
      Element element0 = document0.body();
      StructuralEvaluator.ImmediateParentRun structuralEvaluator_ImmediateParentRun0 = new StructuralEvaluator.ImmediateParentRun(structuralEvaluator_Not0);
      boolean boolean0 = structuralEvaluator_ImmediateParentRun0.evaluateMatch(element0, document0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      Document document0 = Document.createShell("FH6_Po5wifQ");
      StructuralEvaluator.ImmediateParentRun structuralEvaluator_ImmediateParentRun0 = new StructuralEvaluator.ImmediateParentRun(structuralEvaluator_Root0);
      boolean boolean0 = structuralEvaluator_ImmediateParentRun0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Evaluator.IsOnlyOfType evaluator_IsOnlyOfType0 = new Evaluator.IsOnlyOfType();
      StructuralEvaluator.ImmediateParentRun structuralEvaluator_ImmediateParentRun0 = new StructuralEvaluator.ImmediateParentRun(evaluator_IsOnlyOfType0);
      Document document0 = Document.createShell("a.|UV");
      Document document1 = document0.shallowClone();
      boolean boolean0 = structuralEvaluator_ImmediateParentRun0.matches((Element) document0, (Node) document1);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Evaluator.AttributeWithValueNot evaluator_AttributeWithValueNot0 = new Evaluator.AttributeWithValueNot("Data value must not be null", "Data value must not be null");
      Document document0 = Document.createShell("Data value must not be null");
      Element element0 = document0.head();
      StructuralEvaluator.Ancestor structuralEvaluator_Ancestor0 = new StructuralEvaluator.Ancestor(evaluator_AttributeWithValueNot0);
      boolean boolean0 = structuralEvaluator_Ancestor0.evaluateMatch(document0, element0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Evaluator.Id evaluator_Id0 = new Evaluator.Id("rZ]s-V{TZd]r=8@");
      StructuralEvaluator.Ancestor structuralEvaluator_Ancestor0 = new StructuralEvaluator.Ancestor(evaluator_Id0);
      Document document0 = Parser.parseBodyFragment("", "org.jsoup.select.StructuralEvaluator$ImmediateParentRun");
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(structuralEvaluator_Ancestor0);
      boolean boolean0 = structuralEvaluator_Has0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      Document document0 = Document.createShell("FH6_Po5wifQ");
      StructuralEvaluator.ImmediateParentRun structuralEvaluator_ImmediateParentRun0 = new StructuralEvaluator.ImmediateParentRun(structuralEvaluator_Root0);
      StructuralEvaluator.Ancestor structuralEvaluator_Ancestor0 = new StructuralEvaluator.Ancestor(structuralEvaluator_ImmediateParentRun0);
      boolean boolean0 = structuralEvaluator_Ancestor0.evaluateMatch(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      Document document0 = Document.createShell("FH6_Po5wifQ");
      DataNode dataNode0 = new DataNode(":is(>)");
      StructuralEvaluator.ImmediateParentRun structuralEvaluator_ImmediateParentRun0 = new StructuralEvaluator.ImmediateParentRun(structuralEvaluator_Root0);
      StructuralEvaluator.Ancestor structuralEvaluator_Ancestor0 = new StructuralEvaluator.Ancestor(structuralEvaluator_ImmediateParentRun0);
      boolean boolean0 = structuralEvaluator_Ancestor0.evaluateMatch(document0, dataNode0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Evaluator.ContainsData evaluator_ContainsData0 = new Evaluator.ContainsData("");
      Parser parser0 = Parser.xmlParser();
      StringReader stringReader0 = new StringReader("j2>yZt];n_FIhIIZ");
      Document document0 = parser0.parseInput((Reader) stringReader0, "http://www.w3.org/1999/xhtml");
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_ContainsData0);
      boolean boolean0 = structuralEvaluator_Not0.evaluateMatch(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Evaluator[] evaluatorArray0 = new Evaluator[1];
      Evaluator.Tag evaluator_Tag0 = new Evaluator.Tag("");
      evaluatorArray0[0] = (Evaluator) evaluator_Tag0;
      CombiningEvaluator.Or combiningEvaluator_Or0 = new CombiningEvaluator.Or(evaluatorArray0);
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(combiningEvaluator_Or0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      Document document0 = Document.createShell("FH6_Po5wifQ");
      boolean boolean0 = structuralEvaluator_Root0.matches((Element) document0, (Node) document0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      StructuralEvaluator.Is structuralEvaluator_Is0 = new StructuralEvaluator.Is(structuralEvaluator_Root0);
      Document document0 = Document.createShell("FH6_Po5wifQ");
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(structuralEvaluator_Is0);
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(structuralEvaluator_PreviousSibling0);
      boolean boolean0 = structuralEvaluator_Has0.matches(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      StructuralEvaluator.Is structuralEvaluator_Is0 = new StructuralEvaluator.Is(structuralEvaluator_Root0);
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(structuralEvaluator_Is0);
      int int0 = structuralEvaluator_PreviousSibling0.cost();
      assertEquals(9, int0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("org.jsoup.select.StructuralEvaluator$Not");
      Evaluator.Matches evaluator_Matches0 = new Evaluator.Matches(pattern0);
      StructuralEvaluator.Ancestor structuralEvaluator_Ancestor0 = new StructuralEvaluator.Ancestor(evaluator_Matches0);
      String string0 = structuralEvaluator_Ancestor0.toString();
      assertEquals(":matches(org.jsoup.select.StructuralEvaluator$Not) ", string0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      StructuralEvaluator.Root structuralEvaluator_Root0 = new StructuralEvaluator.Root();
      StructuralEvaluator.Is structuralEvaluator_Is0 = new StructuralEvaluator.Is(structuralEvaluator_Root0);
      String string0 = structuralEvaluator_Is0.toString();
      assertEquals(":is(>)", string0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Evaluator.Tag evaluator_Tag0 = new Evaluator.Tag("Rawtext");
      StructuralEvaluator.Not structuralEvaluator_Not0 = new StructuralEvaluator.Not(evaluator_Tag0);
      StructuralEvaluator.PreviousSibling structuralEvaluator_PreviousSibling0 = new StructuralEvaluator.PreviousSibling(structuralEvaluator_Not0);
      String string0 = structuralEvaluator_PreviousSibling0.toString();
      assertEquals(":not(Rawtext) ~ ", string0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("", 2125);
      Regex regex0 = Regex.fromPattern(pattern0);
      Evaluator.Matches evaluator_Matches0 = new Evaluator.Matches(regex0);
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(evaluator_Matches0);
      String string0 = structuralEvaluator_ImmediatePreviousSibling0.toString();
      assertEquals(":matches() + ", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Evaluator.AttributeStarting evaluator_AttributeStarting0 = new Evaluator.AttributeStarting("y|(\"8)A{=\")oPw:#bt");
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_AttributeStarting0);
      StructuralEvaluator.Ancestor structuralEvaluator_Ancestor0 = new StructuralEvaluator.Ancestor(structuralEvaluator_Has0);
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(structuralEvaluator_Ancestor0);
      int int0 = structuralEvaluator_ImmediatePreviousSibling0.cost();
      assertEquals(482, int0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Evaluator.AttributeWithValueNot evaluator_AttributeWithValueNot0 = new Evaluator.AttributeWithValueNot("Data value must not be null", "Data value must not be null");
      StructuralEvaluator.Is structuralEvaluator_Is0 = new StructuralEvaluator.Is(evaluator_AttributeWithValueNot0);
      StructuralEvaluator.ImmediateParentRun structuralEvaluator_ImmediateParentRun0 = new StructuralEvaluator.ImmediateParentRun(structuralEvaluator_Is0);
      structuralEvaluator_ImmediateParentRun0.add(evaluator_AttributeWithValueNot0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Evaluator.ContainsData evaluator_ContainsData0 = new Evaluator.ContainsData("");
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_ContainsData0);
      StructuralEvaluator.ImmediateParentRun structuralEvaluator_ImmediateParentRun0 = new StructuralEvaluator.ImmediateParentRun(structuralEvaluator_Has0);
      String string0 = structuralEvaluator_ImmediateParentRun0.toString();
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Evaluator.Tag evaluator_Tag0 = new Evaluator.Tag("Rawtext");
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_Tag0);
      StructuralEvaluator.ImmediateParentRun structuralEvaluator_ImmediateParentRun0 = new StructuralEvaluator.ImmediateParentRun(structuralEvaluator_Has0);
      int int0 = structuralEvaluator_ImmediateParentRun0.cost();
      assertEquals(12, int0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Pattern pattern0 = Pattern.compile("org.jsoup.select.StructuralEvaluator$Not");
      Evaluator.Matches evaluator_Matches0 = new Evaluator.Matches(pattern0);
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_Matches0);
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("org.jsoup.select.StructuralEvaluator$Not", "[T1MpRg");
      boolean boolean0 = structuralEvaluator_Has0.evaluateMatch(document0, document0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Evaluator.ContainsData evaluator_ContainsData0 = new Evaluator.ContainsData("");
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(evaluator_ContainsData0);
      String string0 = structuralEvaluator_Has0.toString();
      assertEquals(":has(:containsData())", string0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Evaluator.AllElements evaluator_AllElements0 = new Evaluator.AllElements();
      StructuralEvaluator.Is structuralEvaluator_Is0 = new StructuralEvaluator.Is(evaluator_AllElements0);
      StructuralEvaluator.ImmediatePreviousSibling structuralEvaluator_ImmediatePreviousSibling0 = new StructuralEvaluator.ImmediatePreviousSibling(structuralEvaluator_Is0);
      Document document0 = Document.createShell("xV~~4g/}{e(aT;");
      StructuralEvaluator.Has structuralEvaluator_Has0 = new StructuralEvaluator.Has(structuralEvaluator_ImmediatePreviousSibling0);
      structuralEvaluator_Has0.matches(document0, document0);
  }
}
