/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:14:56 GMT 2026
 */

package org.jsoup.internal;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.PipedInputStream;
import java.io.PushbackInputStream;
import java.io.SequenceInputStream;
import java.net.SocketTimeoutException;
import java.nio.ByteBuffer;
import java.util.Enumeration;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jsoup.Progress;
import org.jsoup.internal.ControllableInputStream;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ControllableInputStream_ESTest extends ControllableInputStream_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 261);
      ControllableInputStream controllableInputStream1 = controllableInputStream0.timeout(0L, Integer.MAX_VALUE);
      byte[] byteArray0 = new byte[1];
      // Undeclared exception!
      try { 
        controllableInputStream1.read(byteArray0, Integer.MAX_VALUE, (-1809));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.internal.SimpleBufferedInput", e);
      }
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      byte[] byteArray0 = new byte[24];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) byteArrayInputStream0, (int) (byte)44);
      Progress<Integer> progress0 = (Progress<Integer>) mock(Progress.class, new ViolatedAssumptionAnswer());
      Integer integer0 = new Integer((-542));
      ControllableInputStream controllableInputStream1 = controllableInputStream0.onProgress(79, progress0, integer0);
      // Undeclared exception!
      try { 
        controllableInputStream1.read(byteArray0, 8192, (-411));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.internal.SimpleBufferedInput", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Enumeration<ControllableInputStream> enumeration0 = (Enumeration<ControllableInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      PushbackInputStream pushbackInputStream0 = new PushbackInputStream(sequenceInputStream0, 255);
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) pushbackInputStream0, 8192);
      Progress<Integer> progress0 = (Progress<Integer>) mock(Progress.class, new ViolatedAssumptionAnswer());
      Integer integer0 = new Integer(1);
      ControllableInputStream controllableInputStream1 = controllableInputStream0.onProgress((-834), progress0, integer0);
      ControllableInputStream.readToByteBuffer(controllableInputStream1, 85);
      assertTrue(controllableInputStream1.baseReadFully());
      assertEquals(8192, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Enumeration<ControllableInputStream> enumeration0 = (Enumeration<ControllableInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false, false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      PushbackInputStream pushbackInputStream0 = new PushbackInputStream(sequenceInputStream0, 255);
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) pushbackInputStream0, 8192);
      controllableInputStream0.close();
      assertEquals(8192, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 113);
      controllableInputStream0.allowClose(false);
      controllableInputStream0.close();
      assertEquals(113, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 1038);
      controllableInputStream0.max(0);
      assertEquals(0, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 2450);
      controllableInputStream0.mark(0);
      controllableInputStream0.reset();
      assertEquals(2450, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Enumeration<ControllableInputStream> enumeration0 = (Enumeration<ControllableInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      PushbackInputStream pushbackInputStream0 = new PushbackInputStream(sequenceInputStream0, 255);
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) pushbackInputStream0, 8192);
      try { 
        controllableInputStream0.reset();
        fail("Expecting exception: IOException");
      
      } catch(IOException e) {
         //
         // Resetting to invalid mark
         //
         verifyException("org.jsoup.internal.ControllableInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      byte[] byteArray0 = new byte[8];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      ControllableInputStream.readToByteBuffer(byteArrayInputStream0, (byte)0);
      assertEquals(0, byteArrayInputStream0.available());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      byte[] byteArray0 = new byte[8];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) byteArrayInputStream0, (int) (byte)0, (int) (byte)118);
      // Undeclared exception!
      try { 
        ControllableInputStream.readToByteBuffer(controllableInputStream0, (byte) (-100));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // maxSize must be 0 (unlimited) or larger
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Enumeration<ControllableInputStream> enumeration0 = (Enumeration<ControllableInputStream>) mock(Enumeration.class, new ViolatedAssumptionAnswer());
      doReturn(false).when(enumeration0).hasMoreElements();
      SequenceInputStream sequenceInputStream0 = new SequenceInputStream(enumeration0);
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) sequenceInputStream0, 8192, 8192);
      byte[] byteArray0 = new byte[0];
      int int0 = controllableInputStream0.read(byteArray0);
      assertEquals(0, int0);
      assertEquals(8192, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      PipedInputStream pipedInputStream0 = new PipedInputStream();
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) pipedInputStream0, 0, 0);
      byte[] byteArray0 = new byte[2];
      int int0 = controllableInputStream0.read(byteArray0, 0, 0);
      assertEquals(0, int0);
      assertEquals(0, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 1);
      byte[] byteArray0 = new byte[9];
      controllableInputStream0.timeout((-2728L), (byte)1);
      try { 
        controllableInputStream0.read(byteArray0, (int) (byte)0, (int) (byte)32);
        fail("Expecting exception: SocketTimeoutException");
      
      } catch(SocketTimeoutException e) {
         //
         // Read timeout
         //
         verifyException("org.jsoup.internal.ControllableInputStream", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 0, 0);
      controllableInputStream0.max((-607));
      int int0 = controllableInputStream0.read((byte[]) null, 2191, 0);
      assertEquals((-607), controllableInputStream0.max());
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      byte[] byteArray0 = new byte[8];
      ByteArrayInputStream byteArrayInputStream0 = new ByteArrayInputStream(byteArray0);
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) byteArrayInputStream0, (int) (byte)0, (int) (byte)118);
      ByteBuffer byteBuffer0 = ControllableInputStream.readToByteBuffer(controllableInputStream0, 1651);
      assertEquals(0, byteArrayInputStream0.available());
      assertEquals("java.nio.HeapByteBuffer[pos=0 lim=8 cap=1651]", byteBuffer0.toString());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 0, 0);
      ControllableInputStream controllableInputStream1 = ControllableInputStream.wrap((InputStream) controllableInputStream0, 1666);
      assertEquals(0, controllableInputStream1.max());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      // Undeclared exception!
      try { 
        ControllableInputStream.wrap((InputStream) null, (-1977), (-1977));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be true
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 0, 0);
      controllableInputStream0.mark(0);
      controllableInputStream0.reset();
      assertEquals(0, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 0, 0);
      int int0 = controllableInputStream0.max();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 0, 0);
      controllableInputStream0.inputStream();
      assertEquals(0, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 2450);
      controllableInputStream0.resetFullyRead();
      assertEquals(2450, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 0, 0);
      boolean boolean0 = controllableInputStream0.markSupported();
      assertTrue(boolean0);
      assertEquals(0, controllableInputStream0.max());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      ControllableInputStream controllableInputStream0 = ControllableInputStream.wrap((InputStream) null, 0, 0);
      assertNotNull(controllableInputStream0);
      
      controllableInputStream0.baseReadFully();
      assertEquals(0, controllableInputStream0.max());
  }
}
