/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:15:20 GMT 2026
 */

package org.jsoup.internal;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.HashMap;
import java.util.IdentityHashMap;
import java.util.LinkedHashSet;
import java.util.LinkedList;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.function.Function;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.internal.Functions;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Functions_ESTest extends Functions_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Function<HashMap<Object, LinkedHashSet>, IdentityHashMap<LinkedHashSet<Object>, HashMap<String, String>>> function0 = Functions.identityMapFunction();
      assertNotNull(function0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Function<Object, Map<Integer, HashMap<Integer, Object>>> function0 = Functions.mapFunction();
      assertNotNull(function0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Function<HashMap<String, String>, Set<LinkedList<Object>>> function0 = Functions.setFunction();
      assertNotNull(function0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Function<LinkedHashSet<LinkedHashSet>, List<Integer>> function0 = Functions.listFunction();
      assertNotNull(function0);
  }
}
