/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:13:12 GMT 2026
 */

package org.jsoup;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.HttpStatusException;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HttpStatusException_ESTest extends HttpStatusException_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("", 0, "");
      int int0 = httpStatusException0.getStatusCode();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      HttpStatusException httpStatusException0 = new HttpStatusException("", 0, "");
      String string0 = httpStatusException0.getUrl();
      assertEquals("", string0);
  }
}
