/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:29:56 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ConcurrentModificationException;
import java.util.List;
import java.util.Map;
import java.util.function.Consumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jsoup.helper.HttpConnection;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Range;
import org.jsoup.parser.ParseSettings;
import org.jsoup.parser.Parser;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Attributes_ESTest extends Attributes_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      HttpConnection httpConnection0 = new HttpConnection();
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.add("application/x-www-form-urlencoded", "Content-Type");
      Map<String, String> map0 = attributes1.dataset();
      httpConnection0.data(map0);
      assertFalse(attributes0.isEmpty());
      assertEquals(1, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Document document0 = Parser.parse(",f(0t=c6v0M^qzh.", "fieldset");
      Attributes attributes0 = document0.attributes();
      attributes0.put("fieldset", "I[nb;");
      Attributes attributes1 = attributes0.add("fieldset", "fieldset");
      ParseSettings parseSettings0 = ParseSettings.htmlDefault;
      int int0 = attributes1.deduplicate(parseSettings0);
      assertEquals(1, attributes0.size());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      attributes0.put("-1,-1:-1--1,-1:-1=-1,-1:-1--1,-1:-1", "-1,-1:-1--1,-1:-1=-1,-1:-1--1,-1:-1");
      attributes0.add("-1,-1:-1--1,-1:-1=-1,-1:-1--1,-1:-1", "Y;o>g7[I9lAN\"");
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      int int0 = attributes0.deduplicate(parseSettings0);
      assertFalse(attributes0.isEmpty());
      assertEquals(1, int0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Document document0 = Parser.parse("RawtextEndTagName", "org.jsoup.nodes.Attributes$1");
      Attributes attributes0 = document0.attributes();
      attributes0.add("org.jsoup.nodes.Attributes$1", "org.jsoup.nodes.Attributes$1");
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      int int0 = attributes0.deduplicate(parseSettings0);
      assertEquals(1, attributes0.size());
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      attributes0.add((String) null, "0");
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      // Undeclared exception!
      try { 
        attributes0.deduplicate(parseSettings0);
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      ParseSettings parseSettings0 = ParseSettings.htmlDefault;
      int int0 = attributes0.deduplicate(parseSettings0);
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.userData("^):o", (Object) "^):o");
      attributes1.normalize();
      assertTrue(attributes1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("org.jsoup.nodes.Attributes$1");
      Attributes attributes0 = cDataNode0.attributes();
      attributes0.normalize();
      assertFalse(attributes0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.userData("^):o", (Object) "^):o");
      Attributes attributes2 = attributes0.clone();
      assertTrue(attributes2.equals((Object)attributes0));
      
      Object[] objectArray0 = new Object[9];
      attributes2.vals = objectArray0;
      boolean boolean0 = attributes1.equals(attributes2);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.add("application/x-www-form-urlencoded", "Content-Type");
      CDataNode cDataNode0 = new CDataNode(":6U3x@(Q_<_5G");
      Attributes attributes2 = cDataNode0.attributes();
      boolean boolean0 = attributes1.equals(attributes2);
      assertEquals(1, attributes0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.userData("^):o", (Object) "^):o");
      Attributes attributes2 = attributes0.clone();
      boolean boolean0 = attributes1.equals(attributes2);
      assertNotSame(attributes2, attributes1);
      assertTrue(attributes2.isEmpty());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("");
      Attributes attributes0 = cDataNode0.attributes();
      Attributes attributes1 = attributes0.clone();
      attributes0.put("", "");
      boolean boolean0 = attributes0.equals(attributes1);
      assertEquals(2, attributes0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Object object0 = new Object();
      boolean boolean0 = attributes0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("org.jsoup.nodes.Attributes$1");
      Attributes attributes0 = cDataNode0.attributes();
      boolean boolean0 = attributes0.equals((Object) null);
      assertFalse(attributes0.isEmpty());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      attributes0.put("", true);
      attributes0.html();
      assertFalse(attributes0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("IT[p\"", "/baseUri");
      Attributes attributes0 = document0.attributes();
      Attributes attributes1 = attributes0.add((String) null, "/baseUri");
      // Undeclared exception!
      try { 
        attributes1.toString();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.add("org.jsou!.nodes.Attributes$1", "org.jsou!.nodes.Attributes$1");
      String string0 = attributes1.html();
      assertFalse(attributes0.isEmpty());
      assertEquals(" org.jsou!.nodes.Attributes$1=\"org.jsou!.nodes.Attributes$1\"", string0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Document document0 = Parser.parse("RawtextEndTagName", "org.jsoup.nodes.Attributes$1");
      Attributes attributes0 = document0.attributes();
      List<Attribute> list0 = attributes0.asList();
      assertTrue(list0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.add((String) null, "mpUHr\"aC)^2#1#+oi_");
      // Undeclared exception!
      try { 
        attributes1.asList();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      attributes0.add("org.jsou!.nodes.Attributes$1", "org.jsou!.nodes.Attributes$1");
      attributes0.asList();
      assertFalse(attributes0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.add("016lNb", "016lNb");
      attributes1.size = 4403;
      Consumer<Object> consumer0 = (Consumer<Object>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      // Undeclared exception!
      try { 
        attributes0.forEach(consumer0);
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Range.AttributeRange range_AttributeRange0 = new Range.AttributeRange((Range) null, (Range) null);
      Attributes attributes1 = attributes0.sourceRange("-9Y", range_AttributeRange0);
      Attributes attributes2 = attributes1.sourceRange("D#~0", range_AttributeRange0);
      assertEquals(0, attributes2.size());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Range.AttributeRange range_AttributeRange0 = Range.AttributeRange.UntrackedAttr;
      Attributes attributes1 = attributes0.sourceRange("jsoup.attrs", range_AttributeRange0);
      Attributes attributes2 = attributes1.put("jsoup.attrs", true);
      attributes2.sourceRange("jsoup.attrs");
      assertFalse(attributes0.isEmpty());
      assertEquals(1, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("org.jsoup.nodes.Attributes$1");
      Attributes attributes0 = cDataNode0.attributes();
      attributes0.add("j% lg5Kh[", "org.jsoup.select.Evaluator$IndexEquals");
      Attribute attribute0 = Attribute.createFromEncoded("org.jsoup.nodes.Attributes$1", "org.jsoup.select.Evaluator$IndexEquals");
      Range.AttributeRange range_AttributeRange0 = attribute0.sourceRange();
      Attributes attributes1 = attributes0.sourceRange("org.jsoup.select.Evaluator$IndexEquals", range_AttributeRange0);
      attributes1.sourceRange("j% lg5Kh[");
      assertEquals(2, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Document document0 = Document.createShell("key");
      Attributes attributes0 = document0.attributes;
      attributes0.sourceRange("xI~x:nvd:b[5H7-");
      assertEquals(0, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("org.jsoup.nodes.Attributes$1");
      Attributes attributes0 = cDataNode0.attributes();
      Attribute attribute0 = Attribute.createFromEncoded("org.jsoup.nodes.Attributes$1", "org.jsoup.select.Evaluator$IndexEquals");
      attributes0.put(attribute0);
      assertEquals(2, attributes0.size());
      
      attribute0.sourceRange();
      assertEquals("org.jsoup.select.Evaluator$IndexEquals", attribute0.getValue());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Document document0 = Parser.parse("RawtextEndTagName", "org.jsoup.nodes.Attributes$1");
      Attributes attributes0 = document0.attributes();
      attributes0.add("org.jsoup.nodes.Attributes$1", "org.jsoup.nodes.Attributes$1");
      Attributes attributes1 = new Attributes();
      attributes1.addAll(attributes0);
      assertFalse(attributes1.isEmpty());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      attributes0.addAll(attributes0);
      assertTrue(attributes0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Document document0 = Document.createShell("key");
      Attributes attributes0 = document0.attributes;
      assertEquals(0, attributes0.size());
      
      document0.toggleClass("xI~x:nvd:b[5H7-");
      boolean boolean0 = attributes0.isEmpty();
      assertEquals(1, attributes0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      boolean boolean0 = attributes0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.put("progress", true);
      boolean boolean0 = attributes1.hasDeclaredValueForKeyIgnoreCase("progress");
      assertFalse(attributes0.isEmpty());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      attributes0.put("A$LwJ?lSCfI", "A$LwJ?lSCfI");
      boolean boolean0 = attributes0.hasDeclaredValueForKeyIgnoreCase("A$LwJ?lSCfI");
      assertEquals(1, attributes0.size());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      attributes0.put("progress", true);
      boolean boolean0 = attributes0.hasDeclaredValueForKey("progress");
      assertEquals(1, attributes0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      attributes0.put("", "B,YE8z2X:A=#");
      boolean boolean0 = attributes0.hasDeclaredValueForKey("");
      assertEquals(1, attributes0.size());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("-Fiu+~:%");
      Attributes attributes0 = cDataNode0.attributes();
      boolean boolean0 = attributes0.hasDeclaredValueForKey("Qg>k=.TRs\"b@Ul,~");
      assertFalse(boolean0);
      assertEquals(1, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Document document0 = new Document("49J\")IO39B:vA3\"*oC");
      Attributes attributes0 = document0.attributes;
      Attributes attributes1 = attributes0.put("", true);
      boolean boolean0 = attributes1.hasKeyIgnoreCase("");
      assertTrue(boolean0);
      assertEquals(1, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      boolean boolean0 = attributes0.hasKeyIgnoreCase("Y;o>g7[I9lAN\"");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("org.jsoup.nodes.Attributes$1");
      Attributes attributes0 = cDataNode0.attributes();
      attributes0.removeIgnoreCase("D{&x=\"ews#C9?+c-,j");
      assertEquals(1, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.add("", "data-");
      Object object0 = new Object();
      Attributes attributes2 = attributes1.userData("r}Gv", object0);
      assertFalse(attributes0.isEmpty());
      
      attributes2.removeIgnoreCase("");
      assertEquals(0, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.put("*X~4EV He5cfPV", false);
      assertEquals(0, attributes1.size());
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Document document0 = new Document("version", "version");
      Attributes attributes0 = document0.attributes;
      attributes0.add("Resetting to invalid mark", "Resetting to invalid mark");
      Element element0 = document0.attr("Resetting to invalid mark", "");
      assertSame(document0, element0);
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("org.jsoup.nodes.Attributes$1");
      Attributes attributes0 = cDataNode0.attributes();
      Attributes attributes1 = attributes0.put("s", "s");
      attributes1.put("s", true);
      assertEquals(2, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("c*^");
      Attributes attributes0 = cDataNode0.attributes();
      attributes0.userData("c*^", (Object) cDataNode0);
      attributes0.userData("", (Object) null);
      assertEquals(1, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("c*^");
      Attributes attributes0 = cDataNode0.attributes();
      Attributes attributes1 = attributes0.userData("", (Object) null);
      assertEquals(1, attributes1.size());
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("Ld8\"xY2m5W9.5g");
      Attributes attributes0 = cDataNode0.attributes();
      attributes0.put("/jsoup.userdata", true);
      // Undeclared exception!
      try { 
        attributes0.userData();
        fail("Expecting exception: AssertionError");
      
      } catch(AssertionError e) {
         //
         // no message in exception (getMessage() returned null)
         //
      }
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.put("", "B,YE8z2X:A=#");
      String string0 = attributes1.getIgnoreCase("");
      assertEquals(1, attributes0.size());
      assertEquals("B,YE8z2X:A=#", string0);
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Document document0 = Document.createShell("key");
      Attributes attributes0 = document0.attributes;
      attributes0.attribute("key");
      assertTrue(attributes0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("-Fiu+~:%");
      Attributes attributes0 = cDataNode0.attributes();
      cDataNode0.attr("", "");
      // Undeclared exception!
      try { 
        attributes0.attribute("");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // String must not be empty
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Document document0 = Document.createShell("key");
      Attributes attributes0 = document0.attributes;
      String string0 = attributes0.get("");
      assertEquals("", string0);
      assertTrue(attributes0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test49()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.put("progress", true);
      attributes1.addAll(attributes0);
      assertFalse(attributes0.isEmpty());
      assertEquals(1, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test50()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.add("org.jsou!.nodes.Attributes$1", "org.jsou!.nodes.Attributes$1");
      boolean boolean0 = attributes1.hasDeclaredValueForKeyIgnoreCase("}{RPKb&Smy");
      assertEquals(1, attributes0.size());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test51()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.add("org.jsou!.nodes.Attributes$1", "org.jsou!.nodes.Attributes$1");
      attributes1.put(" org.jsou!.nodes.Attributes$1=\"org.jsou!.nodes.Attributes$1\"", "RawtextEndTagName");
      Attributes attributes2 = attributes1.clone();
      attributes2.addAll(attributes0);
      assertFalse(attributes0.isEmpty());
      assertEquals(2, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test52()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      Attributes attributes1 = attributes0.add("org.jsou!.nodes.Attributes$1", "org.jsou!.nodes.Attributes$1");
      Attributes attributes2 = attributes1.clone();
      attributes2.addAll(attributes0);
      assertFalse(attributes0.isEmpty());
      assertEquals(1, attributes0.size());
  }

  @Test(timeout = 4000)
  public void test53()  throws Throwable  {
      Document document0 = Parser.parse("RawtextEndTagName", "org.jsoup.nodes.Attributes$1");
      Attributes attributes0 = document0.attributes();
      Attributes attributes1 = attributes0.add("org.jsoup.nodes.Attributes$1", "org.jsoup.nodes.Attributes$1");
      attributes1.put(" org.jsoup.nodes.Attributes$1=\"org.jsoup.nodes.Attributes$1\"", "RawtextEndTagName");
      // Undeclared exception!
      try { 
        attributes0.addAll(attributes0);
        fail("Expecting exception: ConcurrentModificationException");
      
      } catch(ConcurrentModificationException e) {
         //
         // Use Iterator#remove() instead to remove attributes while iterating.
         //
         verifyException("org.jsoup.nodes.Attributes$1", e);
      }
  }

  @Test(timeout = 4000)
  public void test54()  throws Throwable  {
      Attributes attributes0 = new Attributes();
      attributes0.add("", "");
      assertFalse(attributes0.isEmpty());
      
      attributes0.put("", false);
      assertTrue(attributes0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test55()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("c*^");
      Attributes attributes0 = cDataNode0.attributes();
      attributes0.hashCode();
  }

  @Test(timeout = 4000)
  public void test56()  throws Throwable  {
      String string0 = Attributes.internalKey((String) null);
      assertEquals("/null", string0);
  }
}
