/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:36:29 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.io.Reader;
import java.io.StringReader;
import java.nio.charset.Charset;
import java.util.LinkedList;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.Connection;
import org.jsoup.helper.HttpConnection;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.DocumentType;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Entities;
import org.jsoup.parser.Parser;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Document_ESTest extends Document_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      document_OutputSettings0.maxPaddingWidth(5);
      assertEquals(5, document_OutputSettings0.maxPaddingWidth());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      // Undeclared exception!
      try { 
        document_OutputSettings0.maxPaddingWidth((-2249));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be true
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      document_OutputSettings0.indentAmount(2225);
      assertEquals(2225, document_OutputSettings0.indentAmount());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      // Undeclared exception!
      try { 
        document_OutputSettings0.indentAmount((-109));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must be true
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Document.OutputSettings.Syntax document_OutputSettings_Syntax0 = Document.OutputSettings.Syntax.html;
      Document.OutputSettings document_OutputSettings1 = document_OutputSettings0.syntax(document_OutputSettings_Syntax0);
      assertFalse(document_OutputSettings1.outline());
      assertEquals(Entities.EscapeMode.base, document_OutputSettings1.escapeMode());
      assertEquals(30, document_OutputSettings1.maxPaddingWidth());
      assertEquals(1, document_OutputSettings1.indentAmount());
      assertTrue(document_OutputSettings1.prettyPrint());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Document document0 = new Document("org.jsoup.nodes.Entities$EscapeMode", "r$s");
      Document document1 = document0.shallowClone();
      assertNotSame(document1, document0);
      assertEquals("r$s", document1.location());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("sa", "");
      Document document1 = document0.shallowClone();
      assertNotSame(document1, document0);
      assertEquals("", document1.location());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Document document0 = Document.createShell("]Q");
      Document document1 = document0.clone();
      assertEquals("]Q", document1.location());
      assertNotSame(document1, document0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Document document0 = Document.createShell("");
      Document document1 = document0.clone();
      assertNotSame(document1, document0);
      assertEquals("", document1.location());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Document document0 = new Document("e|n2Is|0_QWV+>@y'");
      document0.title("Object must not be null");
      document0.title("Object must not be null");
      assertEquals("e|n2Is|0_QWV+>@y'", document0.location());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Document document0 = new Document("OtFCIUFq*", "OtFCIUFq*");
      document0.title("OtFCIUFq*");
      String string0 = document0.title();
      assertEquals("OtFCIUFq*", string0);
      assertEquals("OtFCIUFq*", document0.location());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Document document0 = new Document("e|n2Is|0_QV+>@y'");
      document0.title("e|n2Is|0_QV+>@y'");
      // Undeclared exception!
      try { 
        document0.expectForm("title");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No form elements matched the query 'title' in the document.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Document document0 = new Document((String) null);
      document0.text("TZ#qFnp6%`T7X");
      Element element0 = document0.head();
      assertEquals("head", element0.nodeName());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Document document0 = Document.createShell("8_XRb");
      document0.title();
      assertEquals("8_XRb", document0.location());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Document document0 = new Document("org.jsoup.nodes.Entities$EscapeMode", "r$s");
      document0.prependChild(document0);
      document0.title();
      assertEquals("r$s", document0.location());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Document document0 = Parser.parse("}e/a-h", "}e/a-h");
      document0.documentType();
      assertEquals("}e/a-h", document0.location());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Document document0 = new Document("org.jsoup.parser.StreamParser", "org.jsoup.parser.StreamParser");
      LinkedList<DocumentType> linkedList0 = new LinkedList<DocumentType>();
      DocumentType documentType0 = new DocumentType(":containsOwn(%s)", ":containsOwn(%s)", "");
      linkedList0.add(documentType0);
      document0.appendChildren(linkedList0);
      DocumentType documentType1 = document0.documentType();
      assertEquals("org.jsoup.parser.StreamParser", document0.location());
      assertNotNull(documentType1);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("http://www.w3.org/1999/xhtml", "http://www.w3.org/1999/xhtml");
      document0.documentType();
      assertEquals("http://www.w3.org/1999/xhtml", document0.location());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Document document0 = new Document("$x}*AA-");
      Connection connection0 = document0.connection();
      assertEquals("$x}*AA-", document0.location());
      assertNotNull(connection0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Document document0 = new Document("l0DNMA");
      HttpConnection httpConnection0 = new HttpConnection();
      Document document1 = document0.connection((Connection) httpConnection0);
      Connection connection0 = document1.connection();
      assertEquals("l0DNMA", document1.location());
      assertSame(connection0, httpConnection0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StringReader stringReader0 = new StringReader("");
      Document document0 = parser0.parseInput((Reader) stringReader0, "org.jsoup.nodes.Document");
      String string0 = document0.nodeName();
      assertEquals("#document", string0);
      assertEquals("org.jsoup.nodes.Document", document0.location());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Document document0 = Document.createShell("]Q");
      String string0 = document0.location();
      assertEquals("]Q", string0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Document document0 = Document.createShell("meta[charset]");
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      Document document1 = document0.outputSettings(document_OutputSettings0);
      assertFalse(document_OutputSettings0.outline());
      assertEquals(30, document_OutputSettings0.maxPaddingWidth());
      assertEquals(1, document_OutputSettings0.indentAmount());
      assertEquals("meta[charset]", document1.location());
      assertTrue(document_OutputSettings0.prettyPrint());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Document document0 = new Document((String) null, (String) null);
      Element element0 = document0.createElement("Aqx?i*vm-");
      assertEquals("aqx?i*vm-", element0.normalName());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Document document0 = Parser.parse("t@[' S&Hcs", "ScriptDataEndTagOpen");
      document0.forms();
      assertEquals("ScriptDataEndTagOpen", document0.location());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("_", "org.jsoup.nodes.Document$OutputSettings$Syntax");
      // Undeclared exception!
      try { 
        document0.connection((Connection) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      Document document0 = parser0.parseInput("http://www.w3.org/1999/xhtml", "http://www.w3.org/1999/xhtml");
      Charset charset0 = document0.charset();
      document0.charset(charset0);
      assertEquals("http://www.w3.org/1999/xhtml", document0.location());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Document document0 = Document.createShell("org.jsoup.select.Evaluator$MatchesWholeOwnText");
      String string0 = document0.outerHtml();
      assertEquals("<html>\n <head></head>\n <body></body>\n</html>", string0);
      assertEquals("org.jsoup.select.Evaluator$MatchesWholeOwnText", document0.location());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      assertFalse(document_OutputSettings0.outline());
      
      document_OutputSettings0.outline(true);
      assertTrue(document_OutputSettings0.outline());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      document_OutputSettings0.escapeMode();
  }
}
