/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:45:54 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.internal.QuietAppendable;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Comment;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.DocumentType;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.nodes.TextNode;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class LeafNode_ESTest extends LeafNode_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Comment comment0 = new Comment("$bG?'$dc");
      comment0.attributes();
      assertEquals(0, comment0.childNodeSize());
      
      Comment comment1 = comment0.clone();
      assertNotSame(comment1, comment0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Comment comment0 = new Comment("$bG?'$dc");
      comment0.wrap("S2yBke=zta!wr");
      String string0 = comment0.baseUri();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("z'nBmI&VO\"WX~n[To");
      Node node0 = cDataNode0.attr("", "");
      assertFalse(node0.hasParent());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      DataNode dataNode0 = new DataNode("bgsound");
      String string0 = dataNode0.attr("datalist");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TextNode textNode0 = new TextNode("");
      Element element0 = textNode0.parent();
      assertNull(element0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TextNode textNode0 = new TextNode("/29p");
      Node node0 = textNode0.empty();
      assertEquals(0, node0.childNodeSize());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TextNode textNode0 = new TextNode("??UM (W&JJ#R");
      textNode0.absUrl("??UM (W&JJ#R");
      Node node0 = textNode0.attr("??UM (W&JJ#R", "}^Y$}Q})YF");
      assertSame(textNode0, node0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TextNode textNode0 = new TextNode("??UM (W&JJ#R");
      QuietAppendable quietAppendable0 = QuietAppendable.wrap((Appendable) null);
      textNode0.outerHtmlTail(quietAppendable0, (Document.OutputSettings) null);
      assertFalse(textNode0.hasParent());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("");
      TextNode textNode0 = cDataNode0.text("");
      assertEquals("#cdata", textNode0.nodeName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      DocumentType documentType0 = new DocumentType("", "", "");
      boolean boolean0 = documentType0.hasAttr("");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("org.jsoup.nodes.LeafNode");
      String string0 = cDataNode0.nodeValue();
      assertEquals("org.jsoup.nodes.LeafNode", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("");
      cDataNode0.doSetBaseUri("@=U/s&Rcp|PL3,");
      assertFalse(cDataNode0.hasParent());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("org.jsoup.nodes.LeafNode");
      List<Node> list0 = cDataNode0.ensureChildNodes();
      assertEquals(0, list0.size());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Comment comment0 = new Comment("bgsound");
      Node node0 = comment0.removeAttr("#comment");
      assertEquals("#comment", node0.nodeName());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("");
      cDataNode0.clone();
  }
}
