/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:50:58 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.helper.Regex;
import org.jsoup.nodes.DataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.DocumentType;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.nodes.NodeIterator;
import org.jsoup.parser.Parser;
import org.jsoup.select.Evaluator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NodeIterator_ESTest extends NodeIterator_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Document document0 = Parser.parse("h5", "y$fn 9VerU`vMBr$G8");
      Node[] nodeArray0 = new Node[8];
      nodeArray0[0] = (Node) document0;
      nodeArray0[1] = (Node) document0;
      nodeArray0[2] = (Node) document0;
      nodeArray0[3] = (Node) document0;
      nodeArray0[4] = (Node) document0;
      nodeArray0[5] = (Node) document0;
      nodeArray0[6] = (Node) document0;
      nodeArray0[7] = (Node) document0;
      document0.addChildren(nodeArray0);
      Class<DocumentType> class0 = DocumentType.class;
      NodeIterator<DocumentType> nodeIterator0 = new NodeIterator<DocumentType>(document0, class0);
      // Undeclared exception!
      nodeIterator0.hasNext();
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Document document0 = Document.createShell("3");
      Element element0 = document0.appendElement("3", "");
      Class<DataNode> class0 = DataNode.class;
      NodeIterator<DataNode> nodeIterator0 = new NodeIterator<DataNode>(element0, class0);
      nodeIterator0.remove();
      // Undeclared exception!
      try { 
        nodeIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.nodes.NodeIterator", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Document document0 = Document.createShell("3");
      Class<DataNode> class0 = DataNode.class;
      NodeIterator<DataNode> nodeIterator0 = new NodeIterator<DataNode>(document0, class0);
      // Undeclared exception!
      try { 
        nodeIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.nodes.NodeIterator", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      Document document0 = parser0.parseInput("http://www.w3.org/XML/1998/namespace", "http://www.w3.org/XML/1998/namespace");
      Regex regex0 = Regex.compile("http://www.w3.org/2000/svg");
      Evaluator.Matches evaluator_Matches0 = new Evaluator.Matches(regex0);
      Element element0 = document0.selectFirst((Evaluator) evaluator_Matches0);
      assertNull(element0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Document document0 = Document.createShell("3");
      NodeIterator.from(document0);
  }
}
