/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:52:09 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.regex.Pattern;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Entities;
import org.jsoup.nodes.NodeUtils;
import org.jsoup.nodes.TextNode;
import org.jsoup.parser.Parser;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class NodeUtils_ESTest extends NodeUtils_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Document document0 = Document.createShell("+5\"1");
      Element element0 = document0.createElement("+5\"1");
      Parser parser0 = NodeUtils.parser(element0);
      assertFalse(parser0.isTrackPosition());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Document document0 = Parser.parse("AX)U>]|L]7C", "q6 ");
      Document.OutputSettings document_OutputSettings0 = NodeUtils.outputSettings(document0);
      assertTrue(document_OutputSettings0.prettyPrint());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Document document0 = Document.createShell("+5\"1");
      Element element0 = document0.createElement("+5\"1");
      Document.OutputSettings document_OutputSettings0 = NodeUtils.outputSettings(element0);
      assertEquals(Entities.EscapeMode.base, document_OutputSettings0.escapeMode());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Class<TextNode> class0 = TextNode.class;
      // Undeclared exception!
      try { 
        NodeUtils.selectXpath("Mark invalid", (Element) null, class0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Object must not be null
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Document document0 = Parser.parse("AX)U>]|L]7C", "q6 ");
      Pattern pattern0 = Pattern.compile("");
      document0.getElementsMatchingOwnText(pattern0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      NodeUtils nodeUtils0 = new NodeUtils();
  }
}
