/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:55:36 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.internal.QuietAppendable;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.PseudoTextElement;
import org.jsoup.parser.Tag;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class PseudoTextElement_ESTest extends PseudoTextElement_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Tag tag0 = new Tag("Doctype", "Doctype");
      CDataNode cDataNode0 = new CDataNode("");
      Attributes attributes0 = cDataNode0.attributes();
      PseudoTextElement pseudoTextElement0 = new PseudoTextElement(tag0, "Doctype", attributes0);
      StringBuilder stringBuilder0 = new StringBuilder(2);
      QuietAppendable quietAppendable0 = QuietAppendable.wrap(stringBuilder0);
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      pseudoTextElement0.outerHtmlTail(quietAppendable0, document_OutputSettings0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Tag tag0 = new Tag("");
      CDataNode cDataNode0 = new CDataNode(":nth-child(%d)");
      Attributes attributes0 = cDataNode0.attributes();
      PseudoTextElement pseudoTextElement0 = new PseudoTextElement(tag0, "muted", attributes0);
      pseudoTextElement0.outerHtmlHead((QuietAppendable) null, (Document.OutputSettings) null);
      assertEquals("", pseudoTextElement0.nodeName());
  }
}
