/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 02:57:52 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import java.io.Reader;
import java.io.StringReader;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.CDataNode;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Range;
import org.jsoup.parser.ParseSettings;
import org.jsoup.parser.Parser;
import org.jsoup.parser.Tag;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Range_ESTest extends Range_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Range.AttributeRange range_AttributeRange0 = Range.AttributeRange.UntrackedAttr;
      boolean boolean0 = range_AttributeRange0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Range.Position range_Position0 = new Range.Position((-1), (-1), (-1));
      Range range0 = new Range(range_Position0, range_Position0);
      Range.AttributeRange range_AttributeRange0 = new Range.AttributeRange(range0, range0);
      boolean boolean0 = range_AttributeRange0.equals("-1,-1:-1");
      assertEquals((-1), range_Position0.columnNumber());
      assertFalse(boolean0);
      assertEquals((-1), range_Position0.lineNumber());
      assertEquals((-1), range0.endPos());
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      CDataNode cDataNode0 = new CDataNode("");
      Range.Position range_Position0 = new Range.Position(852, 852, 2015);
      boolean boolean0 = range_Position0.equals(cDataNode0);
      assertEquals(852, range_Position0.lineNumber());
      assertEquals(2015, range_Position0.columnNumber());
      assertEquals(852, range_Position0.pos());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Range.Position range_Position0 = new Range.Position(61, 61, (-1393));
      boolean boolean0 = range_Position0.equals((Object) null);
      assertEquals((-1393), range_Position0.columnNumber());
      assertEquals(61, range_Position0.pos());
      assertEquals(61, range_Position0.lineNumber());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Range.Position range_Position0 = new Range.Position((-913), 0, (-1855));
      boolean boolean0 = range_Position0.isTracked();
      assertEquals((-1855), range_Position0.columnNumber());
      assertEquals((-913), range_Position0.pos());
      assertEquals(0, range_Position0.lineNumber());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Range range0 = Range.Untracked;
      Range.Position range_Position0 = range0.start();
      boolean boolean0 = range_Position0.isTracked();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Range range0 = Range.Untracked;
      Range.Position range_Position0 = new Range.Position(1986, (-50), (-50));
      Range range1 = new Range(range_Position0, range_Position0);
      boolean boolean0 = range0.equals(range1);
      assertEquals((-50), range_Position0.columnNumber());
      assertFalse(boolean0);
      assertEquals(1986, range1.startPos());
      assertEquals((-50), range_Position0.lineNumber());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      Tag tag0 = Tag.valueOf("}j <Ty-5(", parseSettings0);
      Element element0 = new Element(tag0, "}j <Ty-5(");
      Range range0 = Range.of(element0, false);
      assertNotNull(range0);
      
      boolean boolean0 = range0.equals(element0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Range.Position range_Position0 = new Range.Position((-1), (-1), (-1));
      Range range0 = new Range(range_Position0, range_Position0);
      Document document0 = Document.createShell("-1,-1:-1");
      Range range1 = document0.endSourceRange();
      boolean boolean0 = range0.equals(range1);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      Parser parser1 = parser0.setTrackPosition(true);
      StringReader stringReader0 = new StringReader("<cJWMuJAnmozXM s");
      Document document0 = parser1.parseInput((Reader) stringReader0, "jsoup.end");
      Range.of(document0, true);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Range range0 = Range.Untracked;
      boolean boolean0 = range0.isImplicit();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Range.Position range_Position0 = new Range.Position(1986, (-50), (-50));
      Range range0 = new Range(range_Position0, range_Position0);
      boolean boolean0 = range0.isImplicit();
      assertEquals((-50), range_Position0.columnNumber());
      assertTrue(boolean0);
      assertEquals(1986, range0.endPos());
      assertEquals((-50), range_Position0.lineNumber());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Range range0 = Range.Untracked;
      Range.Position range_Position0 = range0.end();
      assertFalse(range_Position0.isTracked());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Range range0 = Range.Untracked;
      int int0 = range0.startPos();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Range range0 = Range.Untracked;
      int int0 = range0.endPos();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Range range0 = Range.Untracked;
      Range.Position range_Position0 = range0.start();
      int int0 = range_Position0.lineNumber();
      assertEquals((-1), int0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Range.Position range_Position0 = new Range.Position((-913), 0, (-1855));
      int int0 = range_Position0.columnNumber();
      assertEquals((-1855), int0);
      assertEquals(0, range_Position0.lineNumber());
      assertEquals((-913), range_Position0.pos());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Range.Position range_Position0 = new Range.Position(3, 3, (-321));
      int int0 = range_Position0.pos();
      assertEquals(3, range_Position0.lineNumber());
      assertEquals(3, int0);
      assertEquals((-321), range_Position0.columnNumber());
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Range.Position range_Position0 = new Range.Position((-913), 0, (-1855));
      Range range0 = new Range(range_Position0, range_Position0);
      range0.hashCode();
      assertEquals((-1855), range_Position0.columnNumber());
      assertEquals(0, range_Position0.lineNumber());
      assertEquals((-913), range0.startPos());
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Attribute attribute0 = new Attribute("Tag [%s] cannot be self-closing; not a void tag", "Tag [%s] cannot be self-closing; not a void tag");
      Range.AttributeRange range_AttributeRange0 = attribute0.sourceRange();
      Range range0 = range_AttributeRange0.nameRange();
      boolean boolean0 = range0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Range.AttributeRange range_AttributeRange0 = Range.AttributeRange.UntrackedAttr;
      Range range0 = range_AttributeRange0.valueRange();
      assertEquals((-1), range0.endPos());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Range.AttributeRange range_AttributeRange0 = Range.AttributeRange.UntrackedAttr;
      String string0 = range_AttributeRange0.toString();
      assertEquals("-1,-1:-1--1,-1:-1=-1,-1:-1--1,-1:-1", string0);
  }
}
