/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:00:12 GMT 2026
 */

package org.jsoup.nodes;

import org.junit.Test;
import static org.junit.Assert.*;
import java.nio.CharBuffer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.internal.QuietAppendable;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Entities;
import org.jsoup.nodes.XmlDeclaration;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class XmlDeclaration_ESTest extends XmlDeclaration_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("?", true);
      xmlDeclaration0.attr("?", (String) null);
      String string0 = xmlDeclaration0.toString();
      assertEquals("<!? ?>", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("im57RA<3,IwU", false);
      xmlDeclaration0.attr("im57RA<3,IwU", "im57RA<3,IwU");
      String string0 = xmlDeclaration0.toString();
      assertEquals("<?im57RA<3,IwU im57ra<3,iwu=\"im57RA&lt;3,IwU\"?>", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("4K5rd3q/ @Q*", false);
      assertEquals("#declaration", xmlDeclaration0.nodeName());
      
      String string0 = xmlDeclaration0.getWholeDeclaration();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("", true);
      char[] charArray0 = new char[1];
      CharBuffer charBuffer0 = CharBuffer.wrap(charArray0);
      QuietAppendable quietAppendable0 = QuietAppendable.wrap(charBuffer0);
      Document.OutputSettings document_OutputSettings0 = new Document.OutputSettings();
      xmlDeclaration0.outerHtmlTail(quietAppendable0, document_OutputSettings0);
      assertEquals(Entities.EscapeMode.base, document_OutputSettings0.escapeMode());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("@7\"({XJf", false);
      xmlDeclaration0.clone();
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      XmlDeclaration xmlDeclaration0 = new XmlDeclaration("4K5rd3q/ @Q*", false);
      xmlDeclaration0.name();
      assertEquals("#declaration", xmlDeclaration0.nodeName());
  }
}
