/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:09:07 GMT 2026
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.List;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.nodes.Node;
import org.jsoup.parser.HtmlTreeBuilder;
import org.jsoup.parser.ParseErrorList;
import org.jsoup.parser.ParseSettings;
import org.jsoup.parser.Parser;
import org.jsoup.parser.TagSet;
import org.jsoup.parser.XmlTreeBuilder;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Parser_ESTest extends Parser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      XmlTreeBuilder xmlTreeBuilder0 = new XmlTreeBuilder();
      Parser parser0 = new Parser(xmlTreeBuilder0);
      String string0 = parser0.unescape("", false);
      assertEquals("", string0);
      assertFalse(parser0.isTrackPosition());
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = Parser.unescapeEntities("niQV", true);
      assertEquals("niQV", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = Parser.unescapeEntities("poBX8[g/&DL}qI;9", true);
      assertEquals("poBX8[g/&DL}qI;9", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      // Undeclared exception!
      try { 
        parser0.setMaxDepth((-4296));
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // maxDepth must be >= 1
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      Parser parser1 = parser0.setTrackErrors((-721));
      assertFalse(parser1.isTrackPosition());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      assertFalse(parser0.isTrackErrors());
      
      parser0.setTrackErrors(110115790);
      parser0.parseInput("http://www.w3.org/1999/xhtml", "http://www.w3.org/XML/1998/namespace");
      assertTrue(parser0.isTrackErrors());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      ParseErrorList parseErrorList0 = parser0.getErrors();
      Parser.parseFragment("n$", (Element) null, "http://www.w3.org/1999/xhtml", parseErrorList0);
      assertFalse(parser0.isTrackErrors());
      assertEquals(512, parser0.getMaxDepth());
      assertFalse(parser0.isTrackPosition());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      assertFalse(parser0.isTrackPosition());
      
      parser0.setTrackPosition(true);
      assertTrue(parser0.isTrackPosition());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Document document0 = Parser.parse("", "");
      assertEquals("", document0.location());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      List<Node> list0 = Parser.parseXmlFragment("5m[xUw|-4:|h1", "http://www.w3.org/1998/Math/MathML");
      assertEquals(1, list0.size());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      Parser parser1 = parser0.settings((ParseSettings) null);
      assertEquals(Integer.MAX_VALUE, parser1.getMaxDepth());
      assertFalse(parser1.isTrackPosition());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      Parser parser1 = parser0.newInstance();
      assertEquals(Integer.MAX_VALUE, parser1.getMaxDepth());
      assertFalse(parser1.isTrackPosition());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      HtmlTreeBuilder htmlTreeBuilder0 = new HtmlTreeBuilder();
      TagSet tagSet0 = htmlTreeBuilder0.defaultTagSet();
      Parser parser1 = parser0.tagSet(tagSet0);
      assertFalse(parser1.isTrackPosition());
      assertEquals(Integer.MAX_VALUE, parser1.getMaxDepth());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      Parser parser1 = parser0.clone();
      assertEquals(512, parser1.getMaxDepth());
      assertFalse(parser1.isTrackPosition());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      XmlTreeBuilder xmlTreeBuilder0 = new XmlTreeBuilder();
      Document document0 = xmlTreeBuilder0.parse("http://www.w3.org/XML/1998/namespace", "mxbv");
      parser0.parseFragmentInput("k>T-t(QDp}o&,~:", (Element) document0, "u/|{DOTF >");
      assertEquals(Integer.MAX_VALUE, parser0.getMaxDepth());
      assertFalse(parser0.isTrackErrors());
      assertFalse(parser0.isTrackPosition());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Parser.parseBodyFragment("Fz)\"nM:?", "b])_(");
  }
}
