/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:07:06 GMT 2026
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.CharacterReader;
import org.jsoup.parser.ParseError;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseError_ESTest extends ParseError_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("H$PxyI)xF");
      ParseError parseError0 = new ParseError(characterReader0, "L@P7$,");
      String string0 = parseError0.toString();
      assertEquals("<1:1>: L@P7$,", string0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Object[] objectArray0 = new Object[2];
      ParseError parseError0 = new ParseError(196, "`", objectArray0);
      String string0 = parseError0.getCursorPos();
      assertEquals("196", string0);
      assertEquals(196, parseError0.getPosition());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("H$PxyI)xF");
      ParseError parseError0 = new ParseError(characterReader0, "L@P7$,");
      String string0 = parseError0.getErrorMessage();
      assertEquals("L@P7$,", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      CharacterReader characterReader0 = new CharacterReader("M['&cp4*/R&cj7[^U");
      Object[] objectArray0 = new Object[5];
      ParseError parseError0 = new ParseError(characterReader0, "M['&cp4*/R&cj7[^U", objectArray0);
      int int0 = parseError0.getPosition();
      assertEquals(0, int0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ParseError parseError0 = new ParseError(0, "");
      assertEquals("0", parseError0.getCursorPos());
  }
}
