/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:10:02 GMT 2026
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attributes;
import org.jsoup.parser.ParseSettings;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class ParseSettings_ESTest extends ParseSettings_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.htmlDefault;
      Attributes attributes0 = new Attributes();
      parseSettings0.normalizeAttributes(attributes0);
      assertTrue(attributes0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      Attributes attributes0 = new Attributes();
      parseSettings0.normalizeAttributes(attributes0);
      assertTrue(parseSettings0.preserveTagCase());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.htmlDefault;
      String string0 = parseSettings0.normalizeAttribute("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      String string0 = parseSettings0.normalizeAttribute("c?r@~=*7;,hOHQ");
      assertEquals("c?r@~=*7;,hOHQ", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.htmlDefault;
      String string0 = parseSettings0.htmlDefault.normalizeTag("Mr%S$0/kLr{cq");
      assertEquals("mr%s$0/klr{cq", string0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      String string0 = parseSettings0.normalizeTag("6Dw@ykv");
      assertEquals("6Dw@ykv", string0);
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String string0 = ParseSettings.normalName("org.jsoup.parser.ParseSettings");
      assertEquals("org.jsoup.parser.parsesettings", string0);
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      ParseSettings parseSettings1 = new ParseSettings(parseSettings0);
      assertTrue(parseSettings1.preserveAttributeCase());
      assertTrue(parseSettings1.preserveTagCase());
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      boolean boolean0 = parseSettings0.preserveAttributeCase();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test9()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      boolean boolean0 = parseSettings0.preserveTagCase();
      assertTrue(boolean0);
  }
}
