/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:11:50 GMT 2026
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.ArrayList;
import java.util.NoSuchElementException;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.Element;
import org.jsoup.parser.Parser;
import org.jsoup.parser.StreamParser;
import org.jsoup.parser.Tag;
import org.jsoup.select.CombiningEvaluator;
import org.jsoup.select.Evaluator;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class StreamParser_ESTest extends StreamParser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      StreamParser streamParser1 = streamParser0.parse("http://www.w3.org/1998/Math/MathML", "http://www.w3.org/2000/svg");
      StreamParser.ElementIterator streamParser_ElementIterator0 = streamParser1.new ElementIterator();
      // Undeclared exception!
      try { 
        streamParser_ElementIterator0.next();
        fail("Expecting exception: NoSuchElementException");
      
      } catch(NoSuchElementException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.StreamParser$ElementIterator", e);
      }
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      // Undeclared exception!
      try { 
        streamParser0.completeFragment();
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("org.jsoup.parser.TreeBuilder", e);
      }
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      // Undeclared exception!
      try { 
        streamParser0.expectNext("");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // String must not be empty
         //
         verifyException("org.jsoup.select.QueryParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      // Undeclared exception!
      try { 
        streamParser0.expectFirst("http://www.w3.org/1999/xhtml");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Could not parse query 'http://www.w3.org/1999/xhtml': unexpected token at '//www.w3.org/1999/xhtml'
         //
         verifyException("org.jsoup.select.QueryParser", e);
      }
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      Tag tag0 = new Tag("", "http://www.w3.org/2000/svg");
      Attributes attributes0 = new Attributes();
      Element element0 = new Element(tag0, "", attributes0);
      StreamParser streamParser1 = streamParser0.parseFragment("http://www.w3.org/XML/1998/namespace", element0, "http://www.w3.org/XML/1998/namespace");
      ArrayList<Evaluator> arrayList0 = new ArrayList<Evaluator>();
      CombiningEvaluator.Or combiningEvaluator_Or0 = new CombiningEvaluator.Or(arrayList0);
      streamParser1.selectFirst((Evaluator) combiningEvaluator_Or0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      // Undeclared exception!
      try { 
        streamParser0.complete();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Must run parse() before calling.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }
}
