/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:13:30 GMT 2026
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.ParseSettings;
import org.jsoup.parser.Tag;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Tag_ESTest extends Tag_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Tag tag0 = new Tag("4vOFc1L", "4vOFc1L", "charset=");
      Tag tag1 = tag0.clone();
      assertTrue(tag1.equals((Object)tag0));
      
      tag1.setSeenSelfClose();
      boolean boolean0 = tag1.equals(tag0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Tag tag0 = new Tag(".h7Q>");
      tag0.tagName = "fhAZF=YQ$-l";
      Tag tag1 = tag0.clone();
      tag0.name("fhAZF=YQ$-l");
      boolean boolean0 = tag0.equals(tag1);
      assertEquals("fhAZF=YQ$-l", tag0.toString());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Tag tag0 = new Tag("DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted");
      Tag tag1 = tag0.clone();
      boolean boolean0 = tag0.equals(tag1);
      assertFalse(tag1.isKnownTag());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Tag tag0 = new Tag("W_R^3@l1]", "W_R^3@l1]", "W_R^3@l1]");
      Tag tag1 = new Tag("", "4T::3Vb)7(3U");
      boolean boolean0 = tag0.equals(tag1);
      assertFalse(tag1.isKnownTag());
      assertEquals("4T::3Vb)7(3U", tag1.namespace());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Tag tag0 = new Tag("DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted");
      Tag tag1 = Tag.valueOf("DoctypePublicIdentifier_singleQuoted");
      boolean boolean0 = tag0.equals(tag1);
      assertEquals("http://www.w3.org/1999/xhtml", tag1.namespace());
      assertFalse(tag1.isKnownTag());
      assertEquals("doctypepublicidentifier_singlequoted", tag1.normalName());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Tag tag0 = new Tag("DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted");
      boolean boolean0 = tag0.equals("DoctypePublicIdentifier_singleQuoted");
      assertFalse(tag0.isKnownTag());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Tag tag0 = new Tag("}-", "}-");
      Tag tag1 = tag0.set((-1600));
      tag1.textState();
      assertTrue(tag0.preserveWhitespace());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      Tag tag0 = Tag.valueOf("77m]'fHnM+Y", parseSettings0);
      tag0.set(512);
      boolean boolean0 = tag0.isFormSubmittable();
      assertTrue(tag0.isKnownTag());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Tag tag0 = Tag.valueOf("!?QvgzUVYN%");
      boolean boolean0 = tag0.isFormSubmittable();
      assertEquals("http://www.w3.org/1999/xhtml", tag0.namespace());
      assertFalse(boolean0);
      assertFalse(tag0.isKnownTag());
      assertEquals("!?qvgzuvyn%", tag0.normalName());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Tag tag0 = new Tag("http://www.w3.org/1999/xhtml", "http://www.w3.org/1999/xhtml", "org.jsoup.parser.Tag");
      tag0.set(64);
      boolean boolean0 = tag0.preserveWhitespace();
      assertTrue(tag0.isKnownTag());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Tag tag0 = Tag.valueOf("!?QvgzUVYN%");
      boolean boolean0 = tag0.preserveWhitespace();
      assertFalse(boolean0);
      assertEquals("http://www.w3.org/1999/xhtml", tag0.namespace());
      assertEquals("!?qvgzuvyn%", tag0.normalName());
      assertFalse(tag0.isKnownTag());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      boolean boolean0 = Tag.isKnownTag("kbd");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      boolean boolean0 = Tag.isKnownTag("DoctypePublicIdentifier_singleQuoted");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Tag tag0 = new Tag("Z>b&bdz", "I\"Vvj!Fe*TRKE");
      assertFalse(tag0.isKnownTag());
      
      tag0.clear(0);
      boolean boolean0 = tag0.isKnownTag();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      ParseSettings parseSettings0 = new ParseSettings(false, false);
      Tag tag0 = Tag.valueOf(" Sb:u142h/_wbX$E(9", " Sb:u142h/_wbX$E(9", parseSettings0);
      boolean boolean0 = tag0.isKnownTag();
      assertFalse(boolean0);
      assertEquals(" Sb:u142h/_wbX$E(9", tag0.namespace());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Tag tag0 = Tag.valueOf("5|O-r( iUN8=");
      Tag.Void = 52;
      tag0.setSeenSelfClose();
      boolean boolean0 = tag0.isSelfClosing();
      assertTrue(tag0.isEmpty());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      ParseSettings parseSettings0 = new ParseSettings(false, true);
      Tag tag0 = Tag.valueOf("2Bk&p4VwCs eW% QG", parseSettings0);
      boolean boolean0 = tag0.isSelfClosing();
      assertEquals("http://www.w3.org/1999/xhtml", tag0.namespace());
      assertFalse(tag0.isKnownTag());
      assertFalse(boolean0);
      assertEquals("2bk&p4vwcs ew% qg", tag0.getName());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Tag tag0 = new Tag((String) null, "+X>DIk>0M$D`x92?GW", "+X>DIk>0M$D`x92?GW");
      Tag tag1 = tag0.set((-1474));
      boolean boolean0 = tag1.isSelfClosing();
      assertTrue(tag0.isEmpty());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Tag tag0 = new Tag((String) null, (String) null);
      assertFalse(tag0.isEmpty());
      
      tag0.options = (-2418);
      boolean boolean0 = tag0.isEmpty();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Tag tag0 = new Tag("DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted");
      boolean boolean0 = tag0.isEmpty();
      assertFalse(boolean0);
      assertFalse(tag0.isKnownTag());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Tag tag0 = new Tag("}-", "}-");
      boolean boolean0 = tag0.isInline();
      assertTrue(boolean0);
      assertFalse(tag0.isKnownTag());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Tag tag0 = new Tag("DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted");
      tag0.set(4);
      boolean boolean0 = tag0.isInline();
      assertTrue(tag0.isBlock());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Tag tag0 = new Tag((String) null, (String) null);
      assertFalse(tag0.formatAsBlock());
      
      tag0.options = (-2418);
      boolean boolean0 = tag0.formatAsBlock();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Tag tag0 = new Tag("DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted", "DoctypePublicIdentifier_singleQuoted");
      boolean boolean0 = tag0.formatAsBlock();
      assertFalse(boolean0);
      assertFalse(tag0.isKnownTag());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Tag tag0 = new Tag((String) null, (String) null);
      assertFalse(tag0.isBlock());
      
      tag0.options = (-2418);
      boolean boolean0 = tag0.isBlock();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Tag tag0 = new Tag("W_R^3@l1]", "W_R^3@l1]", "W_R^3@l1]");
      boolean boolean0 = tag0.isBlock();
      assertFalse(boolean0);
      assertFalse(tag0.isKnownTag());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      ParseSettings parseSettings0 = new ParseSettings(false, false);
      Tag tag0 = Tag.valueOf("]lKq", parseSettings0);
      Tag tag1 = tag0.clear(1);
      assertEquals("http://www.w3.org/1999/xhtml", tag1.namespace());
      assertFalse(tag0.isKnownTag());
      assertFalse(tag1.isFormSubmittable());
      assertFalse(tag1.formatAsBlock());
      assertFalse(tag1.isSelfClosing());
      assertFalse(tag1.preserveWhitespace());
      assertEquals("", tag1.prefix());
      assertFalse(tag1.isBlock());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Tag tag0 = new Tag("W_R^3@l1]", "W_R^3@l1]", "W_R^3@l1]");
      tag0.textState();
      assertFalse(tag0.isKnownTag());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Tag tag0 = new Tag("W_R^3@l1]", "W_R^3@l1]", "W_R^3@l1]");
      String string0 = tag0.localName();
      assertEquals("W_R^3@l1]", string0);
      assertFalse(tag0.isKnownTag());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      ParseSettings parseSettings0 = new ParseSettings(false, true);
      Tag tag0 = Tag.valueOf("2Bk&p4VwCs eW% QG", parseSettings0);
      String string0 = tag0.prefix();
      assertEquals("", string0);
      assertEquals("http://www.w3.org/1999/xhtml", tag0.namespace());
      assertFalse(tag0.isKnownTag());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      ParseSettings parseSettings0 = new ParseSettings(false, false);
      Tag tag0 = Tag.valueOf(" Sb:u142h/_wbX$E(9", " Sb:u142h/_wbX$E(9", parseSettings0);
      String string0 = tag0.prefix();
      assertEquals(" Sb:u142h/_wbX$E(9", tag0.namespace());
      assertFalse(tag0.isKnownTag());
      assertEquals("sb", string0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      ParseSettings parseSettings0 = new ParseSettings(false, true);
      Tag tag0 = Tag.valueOf("2Bk&p4VwCs eW% QG", parseSettings0);
      assertEquals("http://www.w3.org/1999/xhtml", tag0.namespace());
      
      tag0.namespace("org.jsoup.parser.Tag");
      assertEquals("org.jsoup.parser.Tag", tag0.namespace());
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      Tag tag0 = Tag.valueOf("77m]'fHnM+Y", parseSettings0);
      String string0 = tag0.namespace();
      assertFalse(tag0.isKnownTag());
      assertEquals("http://www.w3.org/1999/xhtml", string0);
      assertNotNull(string0);
      assertEquals("77m]'fhnm+y", tag0.normalName());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      ParseSettings parseSettings0 = new ParseSettings(false, true);
      Tag tag0 = Tag.valueOf("2Bk&p4VwCs eW% QG", parseSettings0);
      tag0.hashCode();
      assertEquals("http://www.w3.org/1999/xhtml", tag0.namespace());
      assertFalse(tag0.isKnownTag());
      assertEquals("2bk&p4vwcs ew% qg", tag0.toString());
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      Tag tag0 = Tag.valueOf("77m]'fHnM+Y", parseSettings0);
      String string0 = tag0.toString();
      assertEquals("http://www.w3.org/1999/xhtml", tag0.namespace());
      assertFalse(tag0.isKnownTag());
      assertNotNull(string0);
      assertEquals("77m]'fhnm+y", tag0.normalName());
      assertEquals("77m]'fHnM+Y", string0);
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Tag tag0 = new Tag("7DVX2X*YY", "7DVX2X*YY");
      tag0.name("http://www.w3.org/1999/xhtml");
      tag0.localName();
      assertEquals("http://www.w3.org/1999/xhtml", tag0.normalName());
      assertEquals("http", tag0.prefix());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Tag tag0 = new Tag(".h7Q>");
      Tag tag1 = tag0.name(".h7Q>");
      assertFalse(tag1.isKnownTag());
      
      tag1.options = 256;
      tag0.textState();
      assertEquals(".h7Q>", tag0.localName());
      assertEquals(".h7q>", tag0.normalName());
      assertEquals("http://www.w3.org/1999/xhtml", tag0.namespace());
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Tag tag0 = new Tag(".h7Q>");
      String string0 = tag0.name();
      assertEquals(".h7q>", tag0.normalName());
      assertEquals(".h7Q>", string0);
      assertEquals("http://www.w3.org/1999/xhtml", tag0.namespace());
      assertFalse(tag0.isKnownTag());
      assertNotNull(string0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Tag tag0 = new Tag("o{");
      String string0 = tag0.getName();
      assertEquals("o{", string0);
      assertEquals("http://www.w3.org/1999/xhtml", tag0.namespace());
      assertNotNull(string0);
      assertFalse(tag0.isKnownTag());
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Tag tag0 = new Tag("");
      String string0 = tag0.normalName();
      assertEquals("", string0);
      assertEquals("http://www.w3.org/1999/xhtml", tag0.namespace());
      assertNotNull(string0);
      assertFalse(tag0.isKnownTag());
  }
}
