/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:15:26 GMT 2026
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.shaded.org.mockito.Mockito.*;
import static org.evosuite.runtime.EvoAssertions.*;
import java.util.function.Consumer;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.evosuite.runtime.ViolatedAssumptionAnswer;
import org.jsoup.parser.ParseSettings;
import org.jsoup.parser.Tag;
import org.jsoup.parser.TagSet;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TagSet_ESTest extends TagSet_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TagSet tagSet0 = TagSet.initHtmlDefault();
      Object object0 = new Object();
      boolean boolean0 = tagSet0.equals(object0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TagSet tagSet0 = TagSet.HtmlTagSet;
      boolean boolean0 = tagSet0.equals(tagSet0);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TagSet tagSet0 = TagSet.HtmlTagSet;
      Consumer<Tag> consumer0 = (Consumer<Tag>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      TagSet tagSet1 = tagSet0.onNewTag(consumer0);
      Consumer<Tag> consumer1 = (Consumer<Tag>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      TagSet tagSet2 = tagSet1.onNewTag(consumer1);
      assertSame(tagSet2, tagSet0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TagSet tagSet0 = TagSet.Html();
      Tag tag0 = tagSet0.valueOf("org.jsoup.select.Evaluator$IsOnlyChild", "iAq@T'4:&_'<P{", "iA`X,AE35N", false);
      Tag tag1 = tagSet0.valueOf("org.jsoup.select.Evaluator$IsOnlyChild", "iAq@T'4:&_'<P{", "iA`X,AE35N", false);
      assertSame(tag1, tag0);
      assertEquals("iAq@T'4:&_'<P{", tag1.normalName());
      assertEquals("iAq@T'4:&_'<P{", tag1.name());
      assertNotNull(tag1);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TagSet tagSet0 = TagSet.initHtmlDefault();
      tagSet0.valueOf("http://www.w3.org/1999/xhtml", "n`", "n`", false);
      Tag tag0 = tagSet0.valueOf("m_", "n`", "n`", true);
      assertNotNull(tag0);
      assertEquals("m_", tag0.localName());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      Tag tag0 = Tag.valueOf("select", parseSettings0);
      assertTrue(tag0.isKnownTag());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TagSet tagSet0 = TagSet.Html();
      ParseSettings parseSettings0 = ParseSettings.preserveCase;
      Tag tag0 = tagSet0.valueOf("Oux&", "Oux&", parseSettings0);
      assertNotNull(tag0);
      assertEquals("oux&", tag0.normalName());
      assertEquals("Oux&", tag0.name());
      assertEquals("Oux&", tag0.namespace());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TagSet tagSet0 = TagSet.HtmlTagSet;
      Consumer<Tag> consumer0 = (Consumer<Tag>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      doReturn((String) null).when(consumer0).toString();
      tagSet0.onNewTag(consumer0);
      TagSet tagSet1 = new TagSet(tagSet0);
      assertTrue(tagSet1.equals((Object)tagSet0));
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TagSet tagSet0 = TagSet.Html();
      TagSet tagSet1 = new TagSet(tagSet0);
      assertTrue(tagSet1.equals((Object)tagSet0));
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TagSet tagSet0 = TagSet.HtmlTagSet;
      tagSet0.hashCode();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TagSet tagSet0 = TagSet.initHtmlDefault();
      Consumer<Tag> consumer0 = (Consumer<Tag>) mock(Consumer.class, new ViolatedAssumptionAnswer());
      tagSet0.onNewTag(consumer0);
      ParseSettings parseSettings0 = ParseSettings.htmlDefault;
      Tag tag0 = tagSet0.valueOf("|X148TklJAaXTh>{$^", "|X148TklJAaXTh>{$^", parseSettings0);
      assertNotNull(tag0);
      assertEquals("|X148TklJAaXTh>{$^", tag0.namespace());
      assertEquals("|x148tkljaaxth>{$^", tag0.toString());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TagSet tagSet0 = TagSet.Html();
      // Undeclared exception!
      try { 
        tagSet0.valueOf("", "yZ^ks");
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // String must not be empty
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }
}
