/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:20:17 GMT 2026
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Document;
import org.jsoup.parser.Parser;
import org.jsoup.parser.StreamParser;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Tokeniser_ESTest extends Tokeniser_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Document document0 = Parser.parse("<Lr^/", "http://www.w3.org/1998/Math/MathML");
      assertEquals("http://www.w3.org/1998/Math/MathML", document0.baseUri());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Document document0 = Parser.parse("w]&^;T", "http://www.w3.org/1998/Math/MathML");
      assertEquals("http://www.w3.org/1998/Math/MathML", document0.baseUri());
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Parser parser0 = Parser.htmlParser();
      Document document0 = parser0.parseInput("missing semicolon on [&#%s]", "N?HMkb ?:[Dl");
      assertFalse(document0.hasParent());
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Document document0 = Parser.parse("wd]&;fPG", "http://www.w3.org/1998/Math/MathML");
      assertEquals("", document0.id());
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Parser parser0 = Parser.xmlParser();
      StreamParser streamParser0 = new StreamParser(parser0);
      StreamParser streamParser1 = streamParser0.parse("http://www.w3.org/1999/xhtml", "http://www.w3.org/1999/xhtml");
      assertSame(streamParser1, streamParser0);
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      Parser.parse("<-G:InbxVk", "http://www.w3.org/1999/xhtml");
  }
}
