/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:18:29 GMT 2026
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.TokenData;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TokenData_ESTest extends TokenData_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      tokenData0.append("");
      String string0 = tokenData0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      String string0 = tokenData0.toString();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      tokenData0.append("org.jsoup.parser.TokenData");
      String string0 = tokenData0.value();
      assertEquals("org.jsoup.parser.TokenData", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      tokenData0.append('e');
      tokenData0.append('e');
      String string0 = tokenData0.value();
      assertEquals("ee", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      String string0 = tokenData0.value();
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      tokenData0.append('e');
      tokenData0.append('e');
      tokenData0.set("]dWO9:>jIdC8'Jqo,");
      assertEquals("]dWO9:>jIdC8'Jqo,", tokenData0.toString());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      tokenData0.append("org.jsoup.parser.TokenData");
      boolean boolean0 = tokenData0.hasData();
      assertEquals("org.jsoup.parser.TokenData", tokenData0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      boolean boolean0 = tokenData0.hasData();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      tokenData0.append('.');
      tokenData0.appendCodePoint(0);
      boolean boolean0 = tokenData0.hasData();
      assertEquals(".\u0000", tokenData0.toString());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      tokenData0.appendCodePoint(0);
      tokenData0.append("xn<");
      tokenData0.toString();
      assertEquals("\u0000xn<", tokenData0.toString());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      tokenData0.append('.');
      tokenData0.appendCodePoint(0);
      tokenData0.appendCodePoint(0);
      assertEquals(".\u0000\u0000", tokenData0.toString());
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      tokenData0.append('.');
      tokenData0.appendCodePoint(0);
      tokenData0.append('G');
      assertEquals(".\u0000G", tokenData0.toString());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      tokenData0.append('-');
      tokenData0.append("");
      tokenData0.append("-7\"s");
      assertEquals("--7\"s", tokenData0.toString());
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TokenData tokenData0 = new TokenData();
      tokenData0.set("/");
      assertEquals("/", tokenData0.toString());
  }
}
