/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:23:33 GMT 2026
 */

package org.jsoup.parser;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.parser.TokenQueue;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class TokenQueue_ESTest extends TokenQueue_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("mry.#-7!swi>^fJ?Y,");
      String string0 = tokenQueue0.consumeElementSelector();
      assertEquals("mry", string0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      String string0 = TokenQueue.escapeCssIdentifier("ut5(3mcnJM=u");
      assertEquals("ut5\\(3mcnJM\\=u", string0);
      
      TokenQueue tokenQueue0 = new TokenQueue("ut5(3mcnJM=u");
      tokenQueue0.consumeTo(string0);
      String string1 = tokenQueue0.consumeElementSelector();
      assertEquals("", string1);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      String string0 = TokenQueue.escapeCssIdentifier("mry.#-7!swi>^fJ?Y,");
      assertEquals("mry\\.\\#-7\\!swi\\>\\^fJ\\?Y\\,", string0);
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      String string0 = TokenQueue.escapeCssIdentifier("\u009AIhwVk");
      assertEquals("\u009AIhwVk", string0);
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("z,");
      String string0 = tokenQueue0.consumeCssIdentifier();
      assertEquals("z", string0);
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("t&w<");
      tokenQueue0.consume();
      String string0 = tokenQueue0.chompBalanced('v', ']');
      assertEquals("&", string0);
      
      String string1 = tokenQueue0.consumeCssIdentifier();
      assertEquals("w", string1);
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      String string0 = TokenQueue.escapeCssIdentifier("ut5(3mcnJM=u");
      TokenQueue tokenQueue0 = new TokenQueue("ut5(3mcnJM=u");
      tokenQueue0.consumeTo(string0);
      // Undeclared exception!
      try { 
        tokenQueue0.consumeCssIdentifier();
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // CSS identifier expected, but end of input found
         //
         verifyException("org.jsoup.parser.TokenQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      String string0 = TokenQueue.escapeCssIdentifier("2!\"&md*;g_Imm");
      assertEquals("\\32 \\!\\\"\\&md\\*\\;g_Imm", string0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      String string0 = TokenQueue.escapeCssIdentifier("-ye>uIP0`2");
      assertEquals("-ye\\>uIP0\\`2", string0);
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      String string0 = TokenQueue.escapeCssIdentifier("-");
      assertEquals("\\-", string0);
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      String string0 = TokenQueue.escapeCssIdentifier("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      String string0 = TokenQueue.unescape("");
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      String string0 = TokenQueue.unescape("\\\"\\(\\;Im\\+");
      assertEquals("\"(;Im+", string0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("q64+%{c!d5IH<^O@;");
      String string0 = tokenQueue0.consumeElementSelector();
      assertEquals("q64", string0);
      
      String string1 = tokenQueue0.chompBalanced('+', 'O');
      assertEquals("%{c!d5IH<^", string1);
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("<Bq64+%{c!d5IH<^O@;");
      // Undeclared exception!
      try { 
        tokenQueue0.chompBalanced('<', 'N');
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Did not find balanced marker at 'Bq64+%{c!d5IH<^O@;'
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("3e*w-6\"r?r");
      tokenQueue0.consumeElementSelector();
      // Undeclared exception!
      try { 
        tokenQueue0.chompBalanced('\"', '\"');
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Did not find balanced marker at 'r?r'
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("'");
      // Undeclared exception!
      try { 
        tokenQueue0.chompBalanced('\'', '!');
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Did not find balanced marker at ''
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("sTKgp'>[Ano>-YzEl");
      tokenQueue0.chompBalanced('`', '`');
      tokenQueue0.chompBalanced('`', 'g');
      tokenQueue0.chompBalanced('g', '`');
      // Undeclared exception!
      try { 
        tokenQueue0.chompBalanced('g', '`');
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Did not find balanced marker at 'p'>[Ano>-YzEl'
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("\"(;Im+");
      tokenQueue0.chompBalanced('E', 'E');
      // Undeclared exception!
      try { 
        tokenQueue0.chompBalanced('(', 'E');
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Did not find balanced marker at ';Im+'
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("3e*w-6\"r?r");
      String string0 = tokenQueue0.consumeElementSelector();
      assertEquals("3e*w-6", string0);
      
      String[] stringArray0 = new String[5];
      stringArray0[0] = "\"";
      String string1 = tokenQueue0.consumeToAny(stringArray0);
      assertEquals("", string1);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("Queue did not match expected sequence");
      tokenQueue0.consume();
      String[] stringArray0 = new String[1];
      stringArray0[0] = "Queue did not match expected sequence";
      String string0 = tokenQueue0.consumeToAny(stringArray0);
      assertEquals("ueue did not match expected sequence", string0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("a?^qp>9k}sO");
      // Undeclared exception!
      try { 
        tokenQueue0.consume("?");
        fail("Expecting exception: IllegalStateException");
      
      } catch(IllegalStateException e) {
         //
         // Queue did not match expected sequence
         //
         verifyException("org.jsoup.parser.TokenQueue", e);
      }
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("a?^qp>9k}sO");
      tokenQueue0.consume();
      tokenQueue0.consume("?");
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("         ");
      boolean boolean0 = tokenQueue0.matchChomp(' ');
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("q64+%{c!d5IH<^O@;");
      boolean boolean0 = tokenQueue0.matchChomp('d');
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("");
      tokenQueue0.advance();
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("                  ");
      boolean boolean0 = tokenQueue0.consumeWhitespace();
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("-[Cc?");
      boolean boolean0 = tokenQueue0.matches("-[Cc?");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("\"(;Im+");
      tokenQueue0.remainder();
      String[] stringArray0 = new String[6];
      String string0 = tokenQueue0.consumeToAny(stringArray0);
      assertEquals("", string0);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("                  ");
      boolean boolean0 = tokenQueue0.matchChomp("                  ");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("                  ");
      char[] charArray0 = new char[1];
      boolean boolean0 = tokenQueue0.matchesAny(charArray0);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      String string0 = TokenQueue.escapeCssIdentifier("bph7T\"$d@6QF4?a+$P");
      assertEquals("bph7T\\\"\\$d\\@\\7f 6QF4\\?a\\+\\$P", string0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("<Bq64+%{c!d5IH<^O@;");
      String string0 = tokenQueue0.toString();
      assertEquals("<Bq64+%{c!d5IH<^O@;", string0);
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      TokenQueue tokenQueue0 = new TokenQueue("a?^qp>9k}sO");
      char char0 = tokenQueue0.consume();
      boolean boolean0 = tokenQueue0.matches(char0);
      assertFalse(boolean0);
  }
}
