/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 01:49:58 GMT 2026
 */

package org.jsoup.examples;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.examples.HtmlToPlainText;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;
import org.jsoup.parser.Parser;
import org.jsoup.select.Elements;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class HtmlToPlainText_ESTest extends HtmlToPlainText_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("\n", "\n");
      Elements elements0 = document0.getElementsMatchingOwnText("");
      Elements elements1 = HtmlToPlainText.trimParents(elements0);
      assertEquals(1, elements1.size());
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("sun.net.http.allowRestrictedHeaders", "sun.net.http.allowRestrictedHeaders");
      Elements elements0 = document0.getElementsMatchingOwnText("sun.net.http.allowRestrictedHeaders");
      elements0.add((Element) document0);
      elements0.add((Element) document0);
      elements0.prepend("\nsun.net.http.allmwRestrictedHeaders");
      String string0 = HtmlToPlainText.getPlainText(document0);
      assertEquals(" sun.net.http.allmwRestrictedHeaders sun.net.http.allmwRestrictedHeaders \nsun.net.http.allmwRestrictedHeaderssun.net.http.allowRestrictedHeaders", string0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("\n", "\n");
      Elements elements0 = document0.getElementsMatchingOwnText("");
      elements0.wrap("dt");
      String string0 = HtmlToPlainText.getPlainText(document0);
      assertEquals("dt dt", string0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Element element0 = new Element("dt");
      String string0 = HtmlToPlainText.getPlainText(element0);
      assertEquals("  \n", string0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      String[] stringArray0 = new String[2];
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The 'url' parameter must not be empty.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test5()  throws Throwable  {
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // usage: java -jar jsoup-examples.jar url [selector]
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test6()  throws Throwable  {
      String[] stringArray0 = new String[1];
      // Undeclared exception!
      try { 
        HtmlToPlainText.main(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // The 'url' parameter must not be empty.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test7()  throws Throwable  {
      HtmlToPlainText htmlToPlainText0 = new HtmlToPlainText();
  }

  @Test(timeout = 4000)
  public void test8()  throws Throwable  {
      Document document0 = Parser.parseBodyFragment("\n", "\n");
      HtmlToPlainText.getPlainText(document0);
  }
}
