/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:29:15 GMT 2026
 */

package org.jsoup.safety;

import org.junit.Test;
import static org.junit.Assert.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Document;
import org.jsoup.safety.Cleaner;
import org.jsoup.safety.Safelist;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Cleaner_ESTest extends Cleaner_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test0()  throws Throwable  {
      Safelist safelist0 = Safelist.basicWithImages();
      Cleaner cleaner0 = new Cleaner(safelist0);
      boolean boolean0 = cleaner0.isValidBodyHtml("9>SK?Og<&UMVsb");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test1()  throws Throwable  {
      Safelist safelist0 = new Safelist();
      Cleaner cleaner0 = new Cleaner(safelist0);
      boolean boolean0 = cleaner0.isValidBodyHtml("V<rEI7YfoKOR@>V~}+");
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test2()  throws Throwable  {
      Safelist safelist0 = Safelist.basic();
      Cleaner cleaner0 = new Cleaner(safelist0);
      safelist0.preserveRelativeLinks(true);
      boolean boolean0 = cleaner0.isValidBodyHtml("");
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test3()  throws Throwable  {
      Safelist safelist0 = Safelist.basicWithImages();
      Cleaner cleaner0 = new Cleaner(safelist0);
      Document document0 = new Document(".UZ#V.y/ F)");
      Document document1 = cleaner0.clean(document0);
      assertNotSame(document1, document0);
  }

  @Test(timeout = 4000)
  public void test4()  throws Throwable  {
      Safelist safelist0 = Safelist.basic();
      Cleaner cleaner0 = new Cleaner(safelist0);
      Document document0 = new Document("https://dummy.example/", ";]8FW{");
      cleaner0.isValid(document0);
  }
}
