/*
 * This file was automatically generated by EvoSuite
 * Mon Mar 02 03:31:37 GMT 2026
 */

package org.jsoup.safety;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.jsoup.nodes.Attribute;
import org.jsoup.nodes.Attributes;
import org.jsoup.nodes.Element;
import org.jsoup.safety.Safelist;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Safelist_ESTest extends Safelist_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Safelist.AttributeKey safelist_AttributeKey0 = new Safelist.AttributeKey("1VnV");
      boolean boolean0 = safelist_AttributeKey0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Safelist safelist0 = new Safelist();
      Safelist.TagName safelist_TagName0 = new Safelist.TagName("WSCDT{_}[ErnO .0VG");
      boolean boolean0 = safelist_TagName0.equals(safelist0);
      assertFalse(safelist0.preserveRelativeLinks());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Safelist safelist0 = new Safelist();
      safelist0.getEnforcedAttributes("WSCDT{_}[ErnO .0VG");
      assertFalse(safelist0.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Safelist safelist0 = new Safelist();
      Element element0 = new Element("WSCDT{_}[ErnO .0VG", "'ef5Loh`81C;CZY");
      Attributes attributes0 = new Attributes();
      Attribute attribute0 = new Attribute("/C~GJgA*Nx#'jz", "'ef5Loh`81C;CZY", attributes0);
      safelist0.isSafeAttribute("Sf", element0, attribute0);
      assertFalse(safelist0.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      Safelist safelist1 = safelist0.addEnforcedAttribute("Data", "Data", "Data");
      boolean boolean0 = safelist1.isSafeTag("Data");
      assertTrue(boolean0);
      assertFalse(safelist1.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      boolean boolean0 = safelist0.isSafeTag("");
      assertFalse(boolean0);
      assertFalse(safelist0.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      String[] stringArray0 = new String[3];
      // Undeclared exception!
      try { 
        safelist0.removeProtocols("Data", "FrH9,V'{<+\"e_en11", stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cannot remove a protocol that is not set.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Safelist safelist0 = new Safelist();
      Safelist safelist1 = safelist0.removeEnforcedAttribute("org.jsoup.select.CombiningEvaluator$And", ":all");
      assertFalse(safelist1.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      String[] stringArray0 = new String[3];
      safelist0.addEnforcedAttribute("Data", "((o$w2yGhG2:w", "Data");
      stringArray0[0] = "Data";
      stringArray0[1] = "Data";
      stringArray0[2] = "Data";
      Safelist safelist1 = safelist0.removeAttributes("Data", stringArray0);
      assertFalse(safelist1.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Safelist safelist0 = new Safelist();
      String[] stringArray0 = new String[8];
      stringArray0[0] = "org.jsoup.select.CombiningEvaluator$And";
      stringArray0[1] = ":all";
      stringArray0[2] = ":all";
      stringArray0[3] = "org.jsoup.select.CombiningEvaluator$And";
      stringArray0[4] = "org.jsoup.select.CombiningEvaluator$And";
      stringArray0[5] = ":all";
      stringArray0[6] = ":all";
      stringArray0[7] = ":all";
      Safelist safelist1 = safelist0.removeAttributes(":all", stringArray0);
      assertFalse(safelist1.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Safelist safelist0 = new Safelist();
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        safelist0.removeAttributes("_", stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No attribute names supplied.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      String[] stringArray0 = new String[7];
      // Undeclared exception!
      try { 
        safelist0.addAttributes("RawtextEndTagName", stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // noscript is unsupported in Safelists, due to incompatibilities between parsers with and without script-mode enabled
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      String[] stringArray0 = new String[0];
      // Undeclared exception!
      try { 
        safelist0.addAttributes("c;Vzt2ld)o# 7~7/", stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // No attribute names supplied.
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      String[] stringArray0 = new String[3];
      Safelist safelist1 = safelist0.addEnforcedAttribute("Data", "((o$w2yGhG2:w", "Data");
      stringArray0[0] = "Data";
      // Undeclared exception!
      try { 
        safelist1.removeTags(stringArray0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // String must not be empty
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Safelist safelist0 = new Safelist();
      String[] stringArray0 = new String[3];
      stringArray0[0] = "Lr6)b[IkZ]U";
      stringArray0[1] = "WSCDT{_}[ErnO .0VG";
      stringArray0[2] = "<![CDATA[Lr6)b[IkZ]U]]>";
      Safelist safelist1 = safelist0.removeTags(stringArray0);
      assertFalse(safelist1.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Safelist safelist0 = new Safelist();
      String[] stringArray0 = new String[0];
      Safelist safelist1 = safelist0.addTags(stringArray0);
      assertFalse(safelist1.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      String[] stringArray0 = new String[6];
      stringArray0[0] = "noscript is unsupportec in safelists, due to incompatibilities between parsers with and without script-mode enabled";
      stringArray0[1] = "}an*W0ELvvkY\"NN";
      stringArray0[2] = "#r0~i^f0y@eeO";
      stringArray0[3] = "}an*W0ELvvkY\"NN";
      stringArray0[4] = "#r0~i^f0y@eeO";
      stringArray0[5] = "#r0~i^f0y@eeO";
      safelist0.addProtocols("noscript is unsupportec in safelists, due to incompatibilities between parsers with and without script-mode enabled", "noscript is unsupportec in safelists, due to incompatibilities between parsers with and without script-mode enabled", stringArray0);
      Safelist safelist1 = new Safelist(safelist0);
      assertFalse(safelist1.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      safelist0.addEnforcedAttribute("Data", "caption", "Data");
      safelist0.getEnforcedAttributes("Data");
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      // Undeclared exception!
      try { 
        Safelist.basicWithImages();
       //  fail("Expecting exception: IllegalArgumentException");
       // Unstable assertion
      } catch(IllegalArgumentException e) {
         //
         // noscript is unsupported in Safelists, due to incompatibilities between parsers with and without script-mode enabled
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      safelist0.preserveRelativeLinks(false);
      assertFalse(safelist0.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      Safelist safelist1 = safelist0.addEnforcedAttribute("Data", "Data", "Data");
      Safelist safelist2 = new Safelist(safelist1);
      assertFalse(safelist2.preserveRelativeLinks());
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Safelist safelist0 = Safelist.none();
      boolean boolean0 = safelist0.preserveRelativeLinks();
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      // Undeclared exception!
      try { 
        Safelist.relaxed();
       //  fail("Expecting exception: IllegalArgumentException");
       // Unstable assertion
      } catch(IllegalArgumentException e) {
         //
         // noscript is unsupported in Safelists, due to incompatibilities between parsers with and without script-mode enabled
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      // Undeclared exception!
      try { 
        Safelist.simpleText();
       //  fail("Expecting exception: IllegalArgumentException");
       // Unstable assertion
      } catch(IllegalArgumentException e) {
         //
         // noscript is unsupported in Safelists, due to incompatibilities between parsers with and without script-mode enabled
         //
         verifyException("org.jsoup.helper.Validate", e);
      }
  }
}
